import { useEffect,useState } from 'react'
import { Bike, Edit3, HeartPulse, Plus, Trash2, X } from 'lucide-react'
import MediaCarousel from '../media/MediaCarousel'
import SportsEntryForm from './SportsEntryForm'
import { deleteSport,listSports,saveSport,subscribeSports } from './sportsStore'
import './SportsPage.css'

export default function SportsPage(){const[entries,setEntries]=useState([]),[drawer,setDrawer]=useState(null),[detail,setDetail]=useState(null),[deleting,setDeleting]=useState(null);async function refresh(){setEntries(await listSports())}useEffect(()=>{refresh();return subscribeSports(setEntries)},[]);async function save(entry,media){await saveSport(entry,media);setDrawer(null);await refresh()}async function remove(){await deleteSport(deleting);setDeleting(null);setDetail(null);await refresh()}
return <section className="sports-page"><div className="sports-heading"><div><small>SPORTS & WORKOUTS</small><h2>Sports</h2><p>Visual memories with the numbers that explain each session.</p></div><button className="sports-add" onClick={()=>setDrawer({type:'add'})}><Plus/>Add entry</button></div><div className="sports-feed">{entries.map((entry,index)=><article className="sports-card" key={entry.id} onClick={()=>setDetail(entry)}><MediaCarousel photos={entry.photos} positionX={entry.position_x} positionY={entry.position_y} fallbackClass={`sports-fallback sports-fallback-${index%4}`}/><div className="sports-card-body"><span className="sports-category"><Bike/>{entry.category}</span><h3>{entry.title}</h3><small>{entry.entry_date} · {entry.start_time}</small><div className="sports-metrics"><b>{entry.duration_minutes} min<small>Duration</small></b><b>{entry.distance_km} km<small>Distance</small></b><b>{entry.pace_min_km?entry.pace_min_km.toFixed(1):'—'}<small>Pace</small></b><b>{entry.calories} kcal<small>Energy</small></b><b>{entry.average_hr||'—'} bpm<small>Avg HR</small></b></div><div className="sports-card-actions"><button onClick={e=>{e.stopPropagation();setDrawer({type:'edit',entry})}}><Edit3/>Edit</button><button className="danger" onClick={e=>{e.stopPropagation();setDeleting(entry)}}><Trash2/>Delete</button></div></div></article>)}</div>
{drawer&&<div className="sports-layer"><button className="sports-backdrop" onClick={()=>setDrawer(null)}/><aside className="sports-drawer"><div className="sports-drawer-head"><div><small>{drawer.type==='edit'?'EDIT SPORTS ENTRY':'ADD SPORTS ENTRY'}</small><h2>{drawer.type==='edit'?drawer.entry.title:'Record an activity'}</h2></div><button onClick={()=>setDrawer(null)}><X/></button></div><SportsEntryForm entry={drawer.entry} defaultDate={drawer.defaultDate} onCancel={()=>setDrawer(null)} onSave={save}/></aside></div>}
{detail&&<div className="sports-layer"><button className="sports-backdrop" onClick={()=>setDetail(null)}/><article className="sports-detail"><button className="close" onClick={()=>setDetail(null)}><X/></button><MediaCarousel photos={detail.photos} positionX={detail.position_x} positionY={detail.position_y} fallbackClass="sports-fallback sports-fallback-1"/><div><span className="sports-category">{detail.category}</span><h2>{detail.title}</h2><p>{detail.notes}</p><div className="sports-metrics"><b>{detail.duration_minutes} min<small>Duration</small></b><b>{detail.distance_km} km<small>Distance</small></b><b>{detail.calories} kcal<small>Energy</small></b><b>{detail.average_hr||'—'} bpm<small>Avg HR</small></b><b>RPE {detail.rpe||'—'}<small>Effort</small></b></div></div></article></div>}
{deleting&&<div className="sports-layer"><button className="sports-backdrop" onClick={()=>setDeleting(null)}/><section className="sports-delete"><Trash2/><h2>Delete {deleting.title}?</h2><p>The activity will be removed from Sports, My Life, Log History, and training calculations.</p><div><button onClick={()=>setDeleting(null)}>Cancel</button><button className="danger" onClick={remove}>Delete entry</button></div></section></div>}
</section>}
