import { supabase } from '../../lib/supabaseClient'
import { dataUrlToBlob } from '../media/imagePersistence'
const KEY='fitlife-sports-entries',HISTORY='fitlife-log-history'
const seed=[{id:'sport-1',category:'Cycling',title:'Cycling Commute',entry_date:'2026-09-06',start_time:'17:38',end_time:'18:20',duration_minutes:42,distance_km:14.6,pace_min_km:2.9,calories:381,average_hr:142,max_hr:168,rpe:6,notes:'Steady commute through the city.',photos:[],featured_index:0,position_x:50,position_y:50,sync_status:'synced'},{id:'sport-2',category:'Swimming',title:'Sunday Class Swim',entry_date:'2026-09-04',start_time:'10:00',end_time:'10:42',duration_minutes:42,distance_km:.7,calories:250,average_hr:134,max_hr:154,rpe:5,notes:'Technique-focused pool session.',photos:[],featured_index:0,position_x:50,position_y:50,sync_status:'synced'}]
const safeRows=rows=>rows.map(row=>({...row,photos:(row.photos||[]).filter(photo=>{const source=photo?.signed_url||photo?.url||photo?.data_url||photo?.preview;return source&&!source.startsWith('blob:')})}))
const read=()=>{try{const raw=JSON.parse(localStorage.getItem(KEY));return safeRows(raw||seed)}catch{return seed}}
const write=rows=>{const safe=safeRows(rows);localStorage.setItem(KEY,JSON.stringify(safe));window.dispatchEvent(new CustomEvent('fitlife:sports-changed',{detail:safe}))}
function history(row,remove=false){let rows=[];try{rows=JSON.parse(localStorage.getItem(HISTORY)||'[]')}catch{}const id=`sports:${row.id}`;rows=rows.filter(x=>x.id!==id);if(!remove)rows.unshift({id,source_id:row.id,type:'Sports',title:row.title,date:row.entry_date,time:row.start_time,displayDate:row.entry_date,summary:`${row.duration_minutes||0} min · ${row.distance_km||0} km · ${row.calories||0} kcal`,status:row.sync_status||'pending'});localStorage.setItem(HISTORY,JSON.stringify(rows));window.dispatchEvent(new CustomEvent('fitlife:history-changed',{detail:rows}))}
async function user(){if(!supabase)return null;const{data}=await supabase.auth.getUser();return data.user||null}
async function signedMedia(media){if(!supabase)return[];const output=[];for(const item of media||[]){const{data,error}=await supabase.storage.from('activity-media').createSignedUrl(item.storage_path,60*60*12);if(!error&&data?.signedUrl)output.push({id:item.id,path:item.storage_path,signed_url:data.signedUrl,is_featured:item.is_featured})}return output}
export async function listSports(){const u=await user();if(u){const{data,error}=await supabase.from('sports_entries').select('*, sports_media(*)').is('deleted_at',null).order('entry_date',{ascending:false});if(!error&&data){const rows=[];for(const row of data)rows.push({...row,photos:await signedMedia(row.sports_media)});write(rows);return rows}}return read()}
export async function saveSport(entry,media={}){const u=await user();const localPhotos=(media.photos||entry.photos||[]).filter(photo=>photo?.data_url||photo?.signed_url||photo?.url);const row={...entry,id:entry.id||crypto.randomUUID(),photos:localPhotos,featured_index:media.featured||0,position_x:media.positionX??entry.position_x??50,position_y:media.positionY??entry.position_y??50,sync_status:u?'syncing':navigator.onLine?'local':'offline',updated_at:new Date().toISOString()};let rows=[row,...read().filter(x=>x.id!==row.id)];write(rows);history(row);if(!u)return row
const payload={id:row.id,user_id:u.id,category:row.category,title:row.title,entry_date:row.entry_date,start_time:row.start_time,end_time:row.end_time,duration_minutes:row.duration_minutes,distance_km:row.distance_km,pace_min_km:row.pace_min_km,calories:row.calories,average_hr:row.average_hr,max_hr:row.max_hr,rpe:row.rpe,notes:row.notes,featured_index:row.featured_index,position_x:row.position_x,position_y:row.position_y,updated_at:row.updated_at,deleted_at:null}
const{error}=await supabase.from('sports_entries').upsert(payload,{onConflict:'id'});if(error){row.sync_status='failed';write([row,...rows.filter(x=>x.id!==row.id)]);return row}
await supabase.from('sports_media').delete().eq('sports_id',row.id)
for(let i=0;i<localPhotos.length;i++){const photo=localPhotos[i];if(!photo.data_url)continue;const blob=await dataUrlToBlob(photo.data_url);const path=`${u.id}/sports/${row.id}/${photo.id||crypto.randomUUID()}.webp`;const{error:up}=await supabase.storage.from('activity-media').upload(path,blob,{contentType:'image/webp',upsert:true});if(!up)await supabase.from('sports_media').insert({user_id:u.id,sports_id:row.id,storage_path:path,sort_order:i,is_featured:i===row.featured_index,position_x:row.position_x,position_y:row.position_y})}
row.sync_status='synced';row.photos=(await listSports()).find(x=>x.id===row.id)?.photos||[];write([row,...rows.filter(x=>x.id!==row.id)]);history(row);return row}
export async function deleteSport(row){write(read().filter(x=>x.id!==row.id));history(row,true);const u=await user();if(u)await supabase.from('sports_entries').update({deleted_at:new Date().toISOString()}).eq('id',row.id)}
export function subscribeSports(cb){if(!supabase)return()=>{};const ch=supabase.channel('sports-cross-device').on('postgres_changes',{event:'*',schema:'public',table:'sports_entries'},()=>listSports().then(cb)).subscribe();return()=>supabase.removeChannel(ch)}
