import { useMemo, useState } from 'react'
import { Save } from 'lucide-react'
import MediaEditor from '../media/MediaEditor'
import '../media/media.css'

const today=()=>new Date().toISOString().slice(0,10)
const categories=['Swimming','Cycling','Running','Walking','Strength','Basketball','Football','Tennis / Padel','Badminton','Martial Arts','Volleyball','Other']
export default function SportsEntryForm({entry,onCancel,onSave,defaultDate}){
 const[category,setCategory]=useState(entry?.category||'Walking'),[title,setTitle]=useState(entry?.title||''),[date,setDate]=useState(entry?.entry_date||defaultDate||today()),[start,setStart]=useState(entry?.start_time||'07:30'),[end,setEnd]=useState(entry?.end_time||'08:15'),[distance,setDistance]=useState(entry?.distance_km||''),[calories,setCalories]=useState(entry?.calories||''),[avgHr,setAvgHr]=useState(entry?.average_hr||''),[maxHr,setMaxHr]=useState(entry?.max_hr||''),[rpe,setRpe]=useState(entry?.rpe||''),[notes,setNotes]=useState(entry?.notes||''),[media,setMedia]=useState({photos:entry?.photos||[],files:[],featured:entry?.featured_index||0,positionX:entry?.position_x||50,positionY:entry?.position_y||50})
 const duration=useMemo(()=>{const[a,b]=[start,end].map(x=>{const[h,m]=x.split(':').map(Number);return h*60+m});return Math.max(0,b-a)},[start,end]);const pace=distance&&duration?duration/Number(distance):0
 function submit(e){e.preventDefault();onSave({...entry,category,title:title||`${category} activity`,entry_date:date,start_time:start,end_time:end,duration_minutes:duration,distance_km:Number(distance)||0,pace_min_km:pace,calories:Number(calories)||0,average_hr:Number(avgHr)||null,max_hr:Number(maxHr)||null,rpe:Number(rpe)||null,notes},media)}
 return <form className="sports-form" onSubmit={submit}><div className="sports-form-grid"><label>Activity category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder={`${category} title`}/></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Start time<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End time<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Duration<input value={`${duration} minutes`} disabled/></label><label>Distance, km<input type="number" step="0.01" value={distance} onChange={e=>setDistance(e.target.value)}/></label><label>Pace<input value={pace?`${pace.toFixed(2)} min/km`:'Calculated automatically'} disabled/></label><label>Active calories<input type="number" value={calories} onChange={e=>setCalories(e.target.value)}/></label><label>Average heart rate<input type="number" value={avgHr} onChange={e=>setAvgHr(e.target.value)}/></label><label>Maximum heart rate<input type="number" value={maxHr} onChange={e=>setMaxHr(e.target.value)}/></label><label>RPE, 1–10<input type="number" min="1" max="10" value={rpe} onChange={e=>setRpe(e.target.value)}/></label></div><label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><MediaEditor existing={entry?.photos||[]} positionX={entry?.position_x||50} positionY={entry?.position_y||50} onChange={setMedia}/><div className="sports-form-actions"><button type="button" onClick={onCancel}>Cancel</button><button className="primary"><Save/>Save activity</button></div></form>
}
