const KEYS=['fitlife-sports-entries','fitlife-sports'],nativeSet=localStorage.setItem.bind(localStorage);const read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
function fp(r){return[r.client_entry_id||r.source_id||'',r.category||r.activity_type||'',r.entry_date||r.date||'',r.start_time||r.time||'',+r.duration_minutes||0,+r.distance_km||0].join('|').toLowerCase()}
function dedupe(rows){const out=[],seen=new Map;for(const source of rows||[]){const r={...source};r.client_entry_id||=r.id||crypto.randomUUID();const f=fp(r);if(!seen.has(f)){seen.set(f,out.length);out.push(r)}else{const i=seen.get(f),score=x=>Object.values(x).filter(v=>v!==null&&v!==''&&v!==0).length;out[i]=score(r)>score(out[i])?{...out[i],...r,client_entry_id:out[i].client_entry_id}:{...r,...out[i],client_entry_id:out[i].client_entry_id}}}return out}
function installStore(){KEYS.forEach(k=>nativeSet(k,JSON.stringify(dedupe(read(k,[])))));localStorage.setItem=(k,v)=>{if(KEYS.includes(k)){try{v=JSON.stringify(dedupe(JSON.parse(v)))}catch{}}nativeSet(k,v)}}
function dialog(){let l=document.querySelector('.fl-r-delete-layer');if(l)return l;l=document.createElement('div');l.className='fl-r-delete-layer';l.hidden=true;l.innerHTML='<button class="backdrop"></button><section><small>CONFIRM DELETE</small><h2>Delete record?</h2><p>This action cannot be undone.</p><div><button class="cancel">Cancel</button><button class="danger">Delete</button></div></section>';document.body.appendChild(l);return l}
function ask(title,message,action){const l=dialog(),ok=l.querySelector('.danger'),cancel=l.querySelector('.cancel'),back=l.querySelector('.backdrop');l.querySelector('h2').textContent=title;l.querySelector('p').textContent=message;l.hidden=false;const close=()=>{l.hidden=true;ok.onclick=cancel.onclick=back.onclick=null};cancel.onclick=back.onclick=close;ok.onclick=async()=>{ok.disabled=true;ok.textContent='Deleting…';try{await action();close()}catch(e){alert(e.message||'Delete failed');}finally{ok.disabled=false;ok.textContent='Delete'}}}
function guardBackdrop(){document.addEventListener('input',e=>{const d=e.target.closest('[role=dialog],.sports-drawer,.grateful-drawer,.sports-form,.gratitude-form');if(d)d.dataset.dirty='true'},true);document.addEventListener('click',e=>{const b=e.target.closest('.modal-backdrop,.drawer-backdrop,.sports-backdrop,.grateful-backdrop,[data-backdrop]');if(!b)return;const host=b.parentElement;if(host?.dataset.dirty!=='true')return;e.preventDefault();e.stopImmediatePropagation();if(confirm('Discard unsaved changes?')){host.dataset.dirty='false';host.querySelector('[aria-label=Close],.close,[data-close]')?.click()}},true)}
function interceptDelete(){document.addEventListener('click',e=>{const b=e.target.closest('button,a,[role=button]');if(!b||b.closest('.fl-r-delete-layer')||b.dataset.confirmed)return;const label=`${b.textContent||''} ${b.getAttribute('aria-label')||''}`;if(!/\b(delete|remove)\b/i.test(label))return;e.preventDefault();e.stopImmediatePropagation();const card=b.closest('article,[data-record-id],[role=dialog]'),name=card?.querySelector('h2,h3,b')?.textContent?.trim()||'record';ask(`Delete ${name}?`,`“${name}” and associated media will be removed.`,async()=>{b.dataset.confirmed='1';b.click();setTimeout(()=>delete b.dataset.confirmed,0)})},true)}
function cards(){document.querySelectorAll('.sports-page article,.sports-page .sports-card').forEach(card=>{card.classList.add('fl-r-sport-card');if(card.dataset.slider)return;const img=card.querySelector('img');if(!img)return;card.dataset.slider='1';const host=img.parentElement;host.classList.add('fl-r-media-host');const entry=dedupe(read(KEYS[0],read(KEYS[1],[]))).find(r=>r.title===card.querySelector('h2,h3')?.textContent?.trim()),photos=(entry?.photos||entry?.media||[]).map((p,i)=>({src:p.signed_url||p.url||p.data_url||p.preview,x:p.position_x??p.x??50,y:p.position_y??p.y??50,s:p.crop_scale??p.scale??1,featured:p.featured??i===+(entry?.featured_index||0)})).filter(p=>p.src);if(!photos.length)photos.push({src:img.src,x:entry?.position_x??50,y:entry?.position_y??50,s:entry?.crop_scale??1,featured:true});host.innerHTML=`<div class="fl-r-media-track">${photos.map(p=>`<figure><img src="${p.src}" style="object-position:${p.x}% ${p.y}%;transform:scale(${p.s})">${p.featured?'<span>★ Featured</span>':''}</figure>`).join('')}</div><div class="fl-r-media-dots">${photos.map((_,i)=>`<i class="${i?'':'active'}"></i>`).join('')}</div>`;const track=host.querySelector('.fl-r-media-track');track.onscroll=()=>{const i=Math.round(track.scrollLeft/Math.max(1,track.clientWidth));host.querySelectorAll('.fl-r-media-dots i').forEach((d,n)=>d.classList.toggle('active',n===i))}})}
function init(){installStore();guardBackdrop();interceptDelete();cards();new MutationObserver(cards).observe(document.documentElement,{childList:true,subtree:true});window.fitlifeSportsCompletion={dedupe,ask}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
