import { useEffect, useMemo, useState } from 'react'
import { Activity, Bike, BookHeart, ChevronLeft, ChevronRight, Dumbbell, Flame, HeartPulse, Target, X } from 'lucide-react'
import HabitIcon from '../../lib/habitIconResolver'
import { useDirtyForm, useUnsavedChanges } from '../common/UnsavedChangesProvider'
import './QuickLogDrawer.css'
const read=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
const dateKey=date=>date.toISOString().slice(0,10)
const tabs=[['habits','Habits',Target],['health','Health',HeartPulse],['exercise','Exercise',Dumbbell],['sports','Sports',Bike],['fasting','Fasting',Flame],['gratitude','Gratitude',BookHeart]]
export default function QuickLogDrawer(){const[open,setOpen]=useState(false),[tab,setTab]=useState('habits'),[date,setDate]=useState(new Date()),[draft,setDraft]=useState({});const dirty=useDirtyForm('quick-log',{}),guard=useUnsavedChanges();useEffect(()=>{const handler=event=>{setTab(event.detail?.tab||'habits');setOpen(true)};window.addEventListener('fitlife:open-quick-log',handler);return()=>window.removeEventListener('fitlife:open-quick-log',handler)},[]);useEffect(()=>dirty.check(draft,'Quick Log'),[draft]);function close(){guard?.confirmDiscard(()=>{setOpen(false);setDraft({});dirty.clean()},'Quick Log')}function save(){const day=dateKey(date);Object.entries(draft).forEach(([key,value])=>{localStorage.setItem(`fitlife-quick-log-${key}-${day}`,JSON.stringify(value))});window.dispatchEvent(new CustomEvent('fitlife:quick-log-saved',{detail:{date:day,draft}}));dirty.saved({});setDraft({});setOpen(false)}if(!open)return null;return <div className="fl-quick-layer"><button className="fl-quick-backdrop" onClick={close}/><aside className="fl-quick-drawer"><header><div><small>QUICK LOG</small><h2>Log Day</h2></div><button onClick={close}><X/></button></header><div className="fl-quick-date"><button onClick={()=>setDate(new Date(date.getTime()-86400000))}><ChevronLeft/></button><time>{date.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</time><button disabled={dateKey(date)>=dateKey(new Date())} onClick={()=>setDate(new Date(date.getTime()+86400000))}><ChevronRight/></button></div><nav>{tabs.map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>guard?.confirmDiscard(()=>setTab(id),`${tabs.find(x=>x[0]===tab)?.[1]} tab`)} key={id}><Icon/><span>{label}</span></button>)}</nav><main><TabContent tab={tab} date={date} draft={draft[tab]||{}} setDraft={value=>setDraft(current=>({...current,[tab]:value}))}/></main><footer><button onClick={close}>Cancel</button><button className="save" onClick={save}>Save</button></footer></aside></div>}
function TabContent({tab,date,draft,setDraft}){if(tab==='habits')return <Habits date={date} draft={draft} setDraft={setDraft}/>;if(tab==='health')return <Health draft={draft} setDraft={setDraft}/>;if(tab==='gratitude')return <label className="fl-quick-note">What are you grateful for?<textarea value={draft.note||''} onChange={e=>setDraft({...draft,note:e.target.value})} placeholder="Write a gratitude note..."/></label>;return <section className="fl-quick-link"><Activity/><h3>{tabs.find(x=>x[0]===tab)?.[1]}</h3><p>Open the full module to use its existing detailed form.</p><button onClick={()=>{window.location.hash=tab==='exercise'?'exercises':tab;window.dispatchEvent(new HashChangeEvent('hashchange'))}}>Open {tabs.find(x=>x[0]===tab)?.[1]}</button></section>}
function Habits({date,draft,setDraft}){const habits=read('fitlife-habits',[]).filter(x=>!x.archived&&!x.deleted&&!x.paused);return <section className="fl-quick-list">{habits.map(habit=>{const value=draft[habit.id]||{};return <article key={habit.id}><HabitIcon icon={habit.icon}/><div><b>{habit.name}</b><small>{habit.target_value?`Target: ${habit.target_value} ${habit.unit||''}`:'Binary habit'}</small>{habit.target_value&&<input type="number" value={value.value||''} onChange={e=>setDraft({...draft,[habit.id]:{...value,value:e.target.value}})}/>}</div><button className={value.completed?'done':''} onClick={()=>setDraft({...draft,[habit.id]:{...value,completed:!value.completed}})}>{value.completed?'Done':'Not done'}</button></article>})}</section>}
function Health({draft,setDraft}){const defs=read('fitlife-health-defs-v2',read('fitlife-health-defs',[]));return <section className="fl-quick-list">{defs.map(metric=><label key={metric.id}><span><b>{metric.name}</b><small>{metric.unit||'Value'} · {metric.target?`Target ${metric.target}`:'Baseline not set'}</small></span><input type="number" value={draft[metric.id]||''} onChange={e=>setDraft({...draft,[metric.id]:e.target.value})}/></label>)}</section>}
