const entries=[
{icon:'✅',title:'Morning walk',type:'Habit',date:'Sun, Sep 6, 2026',summary:'Completed · 37 minutes',kind:'Habit'},
{icon:'⏱️',title:'Fasting session',type:'Fasting',date:'Sun, Sep 6, 2026',summary:'16.0 hours · Metabolic switch',kind:'Fasting'},
{icon:'💛',title:'Tiny wins',type:'Grateful',date:'Sun, Sep 6, 2026',summary:'I showed up, stayed consistent, and listened to my body.',kind:'Grateful'},
{icon:'🚴',title:'Cycling Commute',type:'Workout',date:'Sat, Sep 5, 2026',summary:'42 min · 14.6 km · 381 kcal',kind:'Workout'},
{icon:'❤️',title:'Resting heart rate',type:'Health',date:'Sat, Sep 5, 2026',summary:'58 bpm · Within baseline',kind:'Health'},
{icon:'✅',title:'Hydration check',type:'Habit',date:'Sat, Sep 5, 2026',summary:'Completed · 2.5 L',kind:'Habit'},
{icon:'💛',title:'Today I am grateful for',type:'Grateful',date:'Fri, Sep 4, 2026',summary:'Steady energy, supportive routines, and time to recover.',kind:'Grateful'}];
const list=document.querySelector('#list');function render(filter='All'){list.innerHTML='';entries.filter(e=>filter==='All'||e.kind===filter).forEach((e,i)=>{const el=document.createElement('article');el.className='entry';el.innerHTML=`<div class="emoji">${e.icon}</div><div><h3>${e.title}</h3><div class="type">${e.type}</div><small>${e.date}</small></div><div class="summary">${e.summary}</div><div class="entry-actions"><button title="Edit" data-edit="${i}">✎</button><button title="Delete" data-delete="${i}">⌫</button></div>`;list.append(el)})}render();
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('on'));b.classList.add('on');render(b.textContent)});
const overlay=document.querySelector('#overlay');function edit(i){const e=entries[i];overlay.className='overlay';overlay.innerHTML=`<section class="drawer"><div class="drawer-head"><div><small>EDIT LOG ENTRY</small><h2>${e.title}</h2></div><button onclick="closeLayer()">×</button></div><div class="form"><label>Entry type<select><option>${e.type}</option></select></label><label>Title<input value="${e.title}"></label><label>Date<input type="date" value="2026-09-06"></label><label>Details<textarea>${e.summary}</textarea></label><label>Sync status<input value="Synced across devices" disabled></label></div><div class="drawer-footer"><button onclick="closeLayer()">Cancel</button><button class="save" onclick="closeLayer()">Save changes</button></div></section>`}function del(i){const e=entries[i];overlay.className='overlay';overlay.innerHTML=`<section class="confirm"><div class="danger-icon">⌫</div><h2>Delete ${e.title}?</h2><p>This removes the entry from the timeline and queues a deletion for other devices. This action can be undone from the sync history for 30 days.</p><div class="confirm-actions"><button onclick="closeLayer()">Cancel</button><button class="delete" onclick="closeLayer()">Delete entry</button></div></section>`}window.closeLayer=()=>{overlay.className='overlay hidden';overlay.innerHTML=''};document.addEventListener('click',e=>{const a=e.target.closest('[data-edit]'),d=e.target.closest('[data-delete]');if(a)edit(+a.dataset.edit);if(d)del(+d.dataset.delete)});if(location.hash==='#edit')edit(0);if(location.hash==='#delete')del(0);
