const HABITS='fitlife-habits';const LOGS='fitlife-habit-logs';const HISTORY='fitlife-log-history'
const seed=[
{id:'habit-walk',name:'Morning walk',category:'Movement',icon:'Footprints',tracking_type:'minutes',target_mode:'minimum',target_value:10,unit:'min',schedule:[1,2,3,4,5,6,0],color:'#46c985',archived:false},
{id:'habit-italian',name:'Italian lesson',category:'Mindset',icon:'Languages',tracking_type:'binary',target_mode:'exact',target_value:1,unit:'done',schedule:[1,2,3,4,5,6,0],color:'#a78bfa',archived:false},
{id:'habit-water',name:'Water',category:'Health',icon:'Droplets',tracking_type:'quantity',target_mode:'minimum',target_value:2.5,unit:'L',schedule:[1,2,3,4,5,6,0],color:'#38bdf8',archived:false},
{id:'habit-sleep',name:'Sleep range',category:'Recovery',icon:'Moon',tracking_type:'range',target_mode:'range',target_min:7,target_max:9,unit:'h',schedule:[1,2,3,4,5,6,0],color:'#818cf8',archived:false}
]
const today=()=>new Date().toISOString().slice(0,10)
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
const write=(key,value,event)=>{localStorage.setItem(key,JSON.stringify(value));window.dispatchEvent(new CustomEvent(event,{detail:value}))}
export const listHabits=()=>read(HABITS,seed)
export const listHabitLogs=()=>read(LOGS,[{id:'log-walk-1',habit_id:'habit-walk',log_date:today(),value:37,completed:true,is_personal_best:true,note:''},{id:'log-italian-1',habit_id:'habit-italian',log_date:today(),value:1,completed:true,note:''}])
export function saveHabit(habit){const row={...habit,id:habit.id||crypto.randomUUID(),updated_at:new Date().toISOString()};write(HABITS,[row,...listHabits().filter(x=>x.id!==row.id)],'fitlife:habits-changed');return row}
function score(habit,value){if(habit.tracking_type==='binary')return value?1:0;if(habit.target_mode==='range')return value>=habit.target_min&&value<=habit.target_max?1:value<habit.target_min?Math.max(0,value/habit.target_min):Math.max(0,1-(value-habit.target_max)/habit.target_max);if(habit.target_mode==='maximum')return value<=habit.target_value?1:Math.max(0,1-(value-habit.target_value)/habit.target_value);if(habit.target_mode==='exact')return value===habit.target_value?1:Math.max(0,1-Math.abs(value-habit.target_value)/Math.max(1,habit.target_value));return Math.min(1.5,value/Math.max(.0001,habit.target_value))}
export function saveHabitLog(habit,input){const logs=listHabitLogs();const prior=logs.filter(x=>x.habit_id===habit.id&&x.id!==input.id);const achievement=score(habit,Number(input.value));const best=Math.max(0,...prior.map(x=>Number(x.value)||0));const row={...input,id:input.id||crypto.randomUUID(),habit_id:habit.id,completed:achievement>=1,achievement_ratio:achievement,is_personal_best:Number(input.value)>best&&Number(input.value)>0,updated_at:new Date().toISOString(),sync_status:navigator.onLine?'local':'offline'};write(LOGS,[row,...logs.filter(x=>x.id!==row.id&&!(x.habit_id===habit.id&&x.log_date===row.log_date))],'fitlife:habit-logs-changed');updateHistory(habit,row);return row}
function updateHistory(habit,row){let history=read(HISTORY,[]);const id=`habit:${row.id}`;history=history.filter(x=>x.id!==id);history.unshift({id,source_id:row.id,habit_id:habit.id,type:'Habit',title:habit.name,date:row.log_date,time:row.updated_at?.slice(11,16)||'12:00',summary:`${row.value} ${habit.unit}${row.completed?' · Target met':' · In progress'}`,status:row.sync_status||'local'});write(HISTORY,history,'fitlife:history-changed')}
export function deleteHabitLog(row){write(LOGS,listHabitLogs().filter(x=>x.id!==row.id),'fitlife:habit-logs-changed');let history=read(HISTORY,[]).filter(x=>x.id!==`habit:${row.id}`);write(HISTORY,history,'fitlife:history-changed')}
export function habitState(habit,log){if(!log)return'empty';const ratio=log.achievement_ratio??score(habit,Number(log.value));if(log.is_personal_best)return'best';if(ratio>=1.01)return'exceeded';if(ratio>=1)return'met';if(ratio>0)return'partial';return'missed'}
export function currentStreak(habit,logs){let streak=0;const d=new Date();for(let i=0;i<400;i++){const key=d.toISOString().slice(0,10);const scheduled=habit.schedule.includes(d.getDay());if(scheduled){const log=logs.find(x=>x.habit_id===habit.id&&x.log_date===key);if(log?.completed)streak++;else if(key!==today())break}d.setDate(d.getDate()-1)}return streak}
