import {supabase} from '../../lib/supabaseClient'
const H='fitlife-habits',L='fitlife-habit-logs',M='fitlife-habits-v2-migrated'
const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const emit=()=>{window.dispatchEvent(new CustomEvent('fitlife:habits-changed'));window.dispatchEvent(new CustomEvent('fitlife:habit-logs-changed'))}
const user=async()=>{const{data:{user},error}=await supabase.auth.getUser();if(error)throw error;if(!user)throw new Error('Sign in is required.');return user}
const clean=o=>Object.fromEntries(Object.entries(o).filter(([,v])=>v!==undefined))
export const localHabits=()=>read(H,[]).filter(x=>!x.deleted_at)
export const localLogs=()=>read(L,[]).filter(x=>!x.deleted_at)
function cache(habits,logs){localStorage.setItem(H,JSON.stringify(habits));localStorage.setItem(L,JSON.stringify(logs));emit()}
export async function migrateLegacy(){if(localStorage.getItem(M)==='yes')return;const u=await user();for(const old of localHabits()){const row={id:/^[0-9a-f-]{36}$/i.test(String(old.id))?old.id:crypto.randomUUID(),user_id:u.id,name:old.name||'Habit',category:old.category||'Custom',tracking_type:old.tracking_type||'binary',target_mode:old.target_mode||'minimum',target_value:Number(old.target_value??1),target_min:old.target_min??null,target_max:old.target_max??null,unit:old.unit||'done',schedule:Array.isArray(old.schedule)?old.schedule:[1,2,3,4,5,6,0],color:old.color||'#46c985',icon:emoji(old.icon),is_visible:old.is_visible!==false,display_order:Number(old.display_order??100),archived:Boolean(old.archived),source_type:'manual'};const{error}=await supabase.from('habits').upsert(row);if(error)throw error;for(const log of localLogs().filter(x=>x.habit_id===old.id)){const{error:e}=await supabase.from('habit_logs').upsert({id:/^[0-9a-f-]{36}$/i.test(String(log.id))?log.id:crypto.randomUUID(),user_id:u.id,habit_id:row.id,log_date:log.log_date,value:Number(log.value??0),completed:Boolean(log.completed),achievement_ratio:log.achievement_ratio??null,is_personal_best:Boolean(log.is_personal_best),note:log.note||null,source_type:'manual'},{onConflict:'habit_id,log_date'});if(e)throw e}}localStorage.setItem(M,'yes')}
export function emoji(value){const v=String(value||'').trim();if(v&&v.length<=16&&!/^[A-Za-z]+$/.test(v))return v;return({Footprints:'🚶',Droplets:'💧',Moon:'😴',Languages:'🗣️',BookOpen:'📚'}[v]||'✨')}
export async function refreshHabits(){const u=await user();const[{data:habits,error:a},{data:logs,error:b}]=await Promise.all([supabase.from('habits').select('*').eq('user_id',u.id).is('deleted_at',null).order('display_order'),supabase.from('habit_logs').select('*').eq('user_id',u.id).is('deleted_at',null).order('log_date',{ascending:false})]);if(a)throw a;if(b)throw b;cache(habits||[],logs||[]);return{habits:habits||[],logs:logs||[]}}
export async function saveHabit(input){const u=await user();const row=clean({...input,id:input.id||crypto.randomUUID(),user_id:u.id,icon:emoji(input.icon),source_type:'manual',updated_at:new Date().toISOString(),deleted_at:null});const{error}=await supabase.from('habits').upsert(row);if(error)throw error;return refreshHabits()}
export async function deleteHabit(row){const u=await user(),now=new Date().toISOString();const{error}=await supabase.from('habits').update({deleted_at:now,archived_at:now,is_visible:false}).eq('user_id',u.id).eq('id',row.id);if(error)throw error;return refreshHabits()}
export async function saveLog(habit,input){const u=await user(),value=Number(input.value??0),ratio=habit.tracking_type==='binary'?(value?1:0):habit.target_mode==='range'?(value>=habit.target_min&&value<=habit.target_max?1:value/Math.max(.001,habit.target_min)):value/Math.max(.001,habit.target_value||1);const row={id:input.id||crypto.randomUUID(),user_id:u.id,habit_id:habit.id,log_date:input.log_date,value,completed:ratio>=1,achievement_ratio:ratio,is_personal_best:false,note:input.note||null,source_type:'manual',client_updated_at:new Date().toISOString(),deleted_at:null};const{error}=await supabase.from('habit_logs').upsert(row,{onConflict:'habit_id,log_date'});if(error)throw error;return refreshHabits()}
export async function deleteLog(row){const u=await user();const{error}=await supabase.from('habit_logs').update({deleted_at:new Date().toISOString()}).eq('user_id',u.id).eq('id',row.id);if(error)throw error;return refreshHabits()}
export function subscribeHabits(fn){let channels=[],cancelled=false;user().then(u=>{if(cancelled)return;for(const table of ['habits','habit_logs']){const c=supabase.channel(`habits-v2:${table}:${u.id}:${crypto.randomUUID()}`).on('postgres_changes',{event:'*',schema:'public',table,filter:`user_id=eq.${u.id}`},()=>fn());c.subscribe();channels.push(c)}});return()=>{cancelled=true;channels.forEach(c=>supabase.removeChannel(c));channels=[]}}
export function score(h,l){if(!l)return 0;return Math.max(0,Number(l.achievement_ratio??(h.tracking_type==='binary'?(l.value?1:0):Number(l.value)/Math.max(.001,h.target_value||1))))}
export function streak(h,logs){let n=0,d=new Date();for(let i=0;i<400;i++){const k=d.toISOString().slice(0,10);if((h.schedule||[]).includes(d.getDay())){const l=logs.find(x=>x.habit_id===h.id&&x.log_date===k);if(l?.completed)n++;else if(i>0)break}d.setDate(d.getDate()-1)}return n}
