const read=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function dispatchQuick(tab){window.dispatchEvent(new CustomEvent('fitlife:open-quick-log',{detail:{tab}}))}
function installQuickButtons(){document.addEventListener('click',event=>{const button=event.target.closest('button,a,[role="button"]');if(!button)return;const label=`${button.textContent||''} ${button.getAttribute('aria-label')||''}`.trim();if(/log day|quick log/i.test(label)){event.preventDefault();event.stopPropagation();dispatchQuick('habits')}if(/gratitude note/i.test(label)){event.preventDefault();event.stopPropagation();dispatchQuick('gratitude')}},true)}
function activeHabits(){return read('fitlife-habits',[]).filter(h=>!h.archived&&!h.deleted&&!h.paused)}
function updateHabitCounts(root){const count=activeHabits().length;root.querySelectorAll('.su-glance-cards article').forEach(card=>{if(!/habits/i.test(card.textContent))return;const value=card.querySelector('b');if(value){const completed=read('fitlife-habit-logs',[]).filter(x=>x.completed&&x.log_date===new Date().toISOString().slice(0,10)).length;value.textContent=`${completed}/${count}`}})}
function addCalorieCards(root){const grid=root.querySelector('.su-glance-cards');if(!grid||grid.querySelector('[data-calorie-card]'))return;const day=new Date().toISOString().slice(0,10);const sports=read('fitlife-sports-entries',read('fitlife-sports',[])).filter(x=>(x.entry_date||x.date)===day);const workouts=read('fitlife-workout-history-v3',read('fitlife-workout-history',[])).filter(x=>x.date===day);const seen=new Set();const active=[...sports,...workouts].reduce((sum,row)=>{const id=row.source_id||row.activity_id||row.id;if(id&&seen.has(id))return sum;if(id)seen.add(id);return sum+Number(row.calories||0)},0);const profile=read('fitlife-profile',{});const weight=Number(profile.weight_kg||profile.weight),height=Number(profile.height_cm||profile.height),age=Number(profile.age);const sex=profile.bmr_sex||profile.sex;let bmr=null;if(weight&&height&&age&&sex)bmr=Math.round(10*weight+6.25*height-5*age+(String(sex).toLowerCase().startsWith('m')?5:-161));const cards=[['active','🔥','Active Calories',`${Math.round(active)} kcal`,profile.active_calorie_goal?`Goal: ${profile.active_calorie_goal} kcal`:'Goal not set','#f58b42'],['total','⚡','Total Calories',bmr?`${Math.round(bmr+active)} kcal`:'Setup required',bmr?`BMR ${bmr} + Active ${Math.round(active)}`:'Complete BMR profile in Settings','#f1c34d']];cards.forEach(([id,icon,label,value,status,color])=>{const article=document.createElement('article');article.dataset.calorieCard=id;article.style.setProperty('--c',color);article.innerHTML=`<span aria-hidden="true">${icon}</span><small>${label}</small><b>${value}</b><p>${status}</p><i></i>`;grid.appendChild(article)})}
function addPeriodToggles(root){root.querySelectorAll('.su-trend').forEach((card,index)=>{if(card.querySelector('.fl-period-toggle'))return;const toggle=document.createElement('div');toggle.className='fl-period-toggle';['30D','90D','1Y'].forEach((period,i)=>{const button=document.createElement('button');button.textContent=period;button.className=i===0?'active':'';button.onclick=()=>{toggle.querySelectorAll('button').forEach(x=>x.classList.remove('active'));button.classList.add('active');localStorage.setItem(`fitlife-trend-period-${index}`,period);card.dispatchEvent(new CustomEvent('fitlife:trend-period',{detail:{period},bubbles:true}))};toggle.appendChild(button)});card.querySelector('header')?.appendChild(toggle)})}
function update(){const root=document.querySelector('.snapshot-unified');if(!root)return;updateHabitCounts(root);addCalorieCards(root);addPeriodToggles(root)}
installQuickButtons();new MutationObserver(update).observe(document.documentElement,{childList:true,subtree:true});document.readyState==='loading'?document.addEventListener('DOMContentLoaded',update):update();window.fitlifeSnapshotOverhaul={update,openQuickLog:dispatchQuick}
