import { useEffect, useMemo, useRef, useState } from 'react'
import { Activity, Bike, BookHeart, Check, ChevronRight, Dumbbell, Eye, EyeOff, Flame, Footprints, GripVertical, HeartPulse, Moon, RotateCcw, Settings2, Target, Timer, X } from 'lucide-react'
import { CartesianGrid, Line, LineChart, ReferenceArea, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import './SnapshotPage.css'

const MATRIX_CONFIG = [
  { id:'health-matrix', title:'Health & Recovery', x:'Strain', y:'Readiness', corner:{top:'High readiness, low strain',left:'Low readiness, low strain',right:'High readiness, high strain',bottom:'Low readiness, high strain'}, palette:['#efe7d5','#b8d9c6','#5ca69a','#ddb3bd','#9ca8c7','#6685b2','#b76f83','#745d87','#493d59'], now:[76,61], d7:[65,58], d30:[56,53], hasNow:true, has7D:true, has30D:true, states:['Recovery needed','Balanced recovery','Ready to perform','Low readiness, low strain','Moderate readiness and strain','Productive momentum','Overreaching risk','High strain, moderate readiness','High strain, high readiness'] },
  { id:'training-matrix', title:'Sports & Workouts', x:'Intensity', y:'Volume', corner:{top:'High volume, low intensity',left:'Low volume, low intensity',right:'High volume, high intensity',bottom:'Low volume, high intensity'}, palette:['#eee6cd','#c5d9a7','#69ad7d','#d9b77d','#75aaa8','#477fa5','#bc7554','#7869a7','#424872'], now:[68,72], d7:[61,64], d30:[54,57], hasNow:true, has7D:true, has30D:false, states:['Low training load','Building consistency','High-volume base','Low volume, high intensity','Balanced training load','Productive training','Intensity overload','Heavy training block','Peak training demand'] },
  { id:'habits-matrix', title:'Habits & Mindfulness', x:'Rest', y:'Consistency', corner:{top:'High consistency, high rest',left:'High consistency, low rest',right:'Low consistency, high rest',bottom:'Low consistency, low rest'}, palette:['#ead9df','#c9badd','#8089bd','#d9c8ca','#96bbb5','#6494a5','#add7ba','#68b19d','#566e9c'], now:[72,82], d7:[64,73], d30:[55,66], hasNow:true, has7D:false, has30D:true, states:['Routine disrupted','Rebuilding rhythm','Consistent but under-rested','Low consistency, high rest','Balanced routine','Sustainable rhythm','High consistency, low rest','Strong consistency','Consistent and restored'] }
]
const DEFAULT_ORDER=['matrices','glance','health','fasting','timeline']
const DEFAULT_VISIBLE={matrices:true,glance:true,health:true,fasting:true,timeline:true}
const METRICS=[
 {id:'sleep',label:'Sleep',unit:'h',icon:Moon,color:'#8b5cf6',target:[7,9],value:8.1},
 {id:'steps',label:'Steps',unit:'steps',icon:Footprints,color:'#38d38b',target:8000,value:9257},
 {id:'rhr',label:'RHR',unit:'bpm',icon:HeartPulse,color:'#ef6f7d',target:[55,65],value:61},
 {id:'hrv',label:'HRV',unit:'ms',icon:Activity,color:'#38bdf8',target:60,value:67}
]
const WIDGETS={matrices:'Bivariate matrices',glance:'Today at a glance',health:'Health metrics',fasting:'Active fast',timeline:'Today’s timeline'}

function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function sameDay(value){return value===new Date().toISOString().slice(0,10)}
function metricSeries(metric,period){const count=period==='7D'?7:30;return Array.from({length:count},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(count-1-i));const wave=Math.sin(i*.8)*(metric.id==='steps'?1250:metric.id==='hrv'?5:metric.id==='rhr'?2:.55);return{label:period==='7D'?new Intl.DateTimeFormat('en-GB',{weekday:'short'}).format(d):new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short'}).format(d),value:Math.max(0,Number((metric.value+wave).toFixed(metric.id==='steps'?0:1)))}})}

export default function SnapshotPage(){
 const[edit,setEdit]=useState(false)
 const[order,setOrder]=useState(()=>read('fitlife-snapshot-order',DEFAULT_ORDER))
 const[visible,setVisible]=useState(()=>read('fitlife-snapshot-visible',DEFAULT_VISIBLE))
 const[glanceVisible,setGlanceVisible]=useState(()=>read('fitlife-snapshot-glance',{sleep:true,steps:true,fasting:true,habits:true,workout:true,rhr:false}))
 const[settingsOpen,setSettingsOpen]=useState(false)
 const[dragging,setDragging]=useState(null)
 const[dropIndex,setDropIndex]=useState(null)
 const dragRef=useRef(null)
 useEffect(()=>{localStorage.setItem('fitlife-snapshot-order',JSON.stringify(order));localStorage.setItem('fitlife-snapshot-visible',JSON.stringify(visible));localStorage.setItem('fitlife-snapshot-glance',JSON.stringify(glanceVisible))},[order,visible,glanceVisible])
 useEffect(()=>{const sync=()=>setTimeline(read('fitlife-log-history',[]));addEventListener('fitlife:history-changed',sync);addEventListener('storage',sync);return()=>{removeEventListener('fitlife:history-changed',sync);removeEventListener('storage',sync)}},[])
 const[history,setTimeline]=useState(()=>read('fitlife-log-history',[]))
 const fasting=useMemo(()=>read('fitlife-fasting-sessions-v4',read('fitlife-fasting-sessions',[])).find(x=>x.status==='active'),[])
 const habits=read('fitlife-habit-logs',[]).filter(x=>sameDay(x.log_date))
 const workouts=read('fitlife-workout-history-v3',read('fitlife-workout-history',[])).filter(x=>sameDay(x.date))
 const todayHistory=history.filter(x=>sameDay(x.date||x.entry_date)).sort((a,b)=>(b.time||'').localeCompare(a.time||''))

 function startDrag(id,index,event){if(!edit)return;setDragging(id);setDropIndex(index);dragRef.current={id,index,startY:event.clientY};event.currentTarget.setPointerCapture?.(event.pointerId)}
 function moveDrag(event){if(!edit||!dragRef.current)return;const cards=[...document.querySelectorAll('[data-snapshot-widget]')];const y=event.clientY;let next=cards.length-1;cards.forEach((card,index)=>{const r=card.getBoundingClientRect();if(y<r.top+r.height/2&&next===cards.length-1)next=index});setDropIndex(next)}
 function endDrag(){if(!dragRef.current)return;const from=order.indexOf(dragRef.current.id);const to=Math.max(0,Math.min(order.length-1,dropIndex??from));if(from!==to){const next=[...order];const[item]=next.splice(from,1);next.splice(to,0,item);setOrder(next)}setDragging(null);setDropIndex(null);dragRef.current=null}
 function reset(){setOrder(DEFAULT_ORDER);setVisible(DEFAULT_VISIBLE);setGlanceVisible({sleep:true,steps:true,fasting:true,habits:true,workout:true,rhr:false})}
 const components={
  matrices:<MatrixSection/>,
  glance:<GlanceSection config={glanceVisible} metrics={METRICS} fasting={fasting} habits={habits} workouts={workouts}/>,
  health:<HealthSection metrics={METRICS}/>,
  fasting:<FastSection fast={fasting}/>,
  timeline:<TimelineSection rows={todayHistory}/>
 }
 return <section className={`snapshot-v1 ${edit?'is-editing':''}`}><header className="snapshot-header"><div><small>COMMAND CENTER</small><h2>Snapshot</h2><p>Live values sourced from Health, Habits, Fasting, Workouts and Log History.</p></div><div><button onClick={()=>setSettingsOpen(true)}><Settings2/>Quick settings</button><button className={edit?'active':''} onClick={()=>setEdit(!edit)}><GripVertical/>{edit?'Done':'Edit dashboard'}</button></div></header>
 {edit&&<div className="edit-banner"><span>Drag cards with the handle. Other cards move automatically.</span><button onClick={reset}><RotateCcw/>Reset layout</button></div>}
 <div className="snapshot-stack" onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag}>{order.map((id,index)=>visible[id]&&<div key={id} data-snapshot-widget={id} className={`widget-shell ${dragging===id?'dragging':''} ${dropIndex===index&&dragging!==id?'drop-target':''}`}><div className="widget-controls"><button className="drag-handle" onPointerDown={e=>startDrag(id,index,e)}><GripVertical/></button><span>{WIDGETS[id]}</span><button onClick={()=>setVisible({...visible,[id]:false})}><EyeOff/></button></div>{components[id]}</div>)}</div>
 {settingsOpen&&<SnapshotSettings visible={visible} setVisible={setVisible} glance={glanceVisible} setGlance={setGlanceVisible} onClose={()=>setSettingsOpen(false)}/>}</section>
}

function MatrixSection(){return <section className="matrix-section"><div className="matrix-grid-v1">{MATRIX_CONFIG.map(matrix=><MatrixCard key={matrix.id} matrix={matrix}/>)}</div></section>}
function MatrixCard({matrix}){const[selected,setSelected]=useState(null);const[markers,setMarkers]=useState({now:true,d7:true,d30:true});const[recordOpen,setRecordOpen]=useState(false);const currentIndex=Math.max(0,Math.min(8,Math.floor(matrix.now[1]/34)*3+Math.floor(matrix.now[0]/34)));return <article className="matrix-card-v1"><header><div><small>ACTIVITY AT A GLANCE</small><h3>{matrix.title}</h3></div><span>90D</span></header><div className="marker-toggles"><button className={markers.d30?'active':''} onClick={()=>setMarkers({...markers,d30:!markers.d30})}>30D</button><button className={markers.d7?'active':''} onClick={()=>setMarkers({...markers,d7:!markers.d7})}>7D</button><button className={markers.now?'active':''} onClick={()=>setMarkers({...markers,now:!markers.now})}>X</button></div><div className="matrix-layout"><div className="matrix-stage"><span className="corner top">{matrix.corner.top}</span><span className="corner left">{matrix.corner.left}</span><span className="corner right">{matrix.corner.right}</span><span className="corner bottom">{matrix.corner.bottom}</span><div className="diamond-v1"><div className="diamond-cells">{matrix.palette.map((color,index)=><button key={index} style={{background:color}} onMouseEnter={()=>setSelected(index)} onMouseLeave={()=>setSelected(null)} onClick={()=>setSelected(index)} aria-label={matrix.states[index]}/>)}</div>{markers.now&&<Marker value="X" point={matrix.now} actual available={matrix.hasNow}/>} {markers.d7&&<Marker value="7D" point={matrix.d7} available={matrix.has7D}/>} {markers.d30&&<Marker value="30D" point={matrix.d30} available={matrix.has30D}/>}</div></div>{selected!==null&&<div className="matrix-tooltip"><b>{matrix.states[selected]}</b><p>{selected<3?'Lower combined load with recovery emphasis.':selected<6?'Middle-state balance with mixed inputs.':'Higher combined demand requiring closer review.'}</p></div>}</div><div className="matrix-footer-v3"><div><b>Current state: {matrix.states[currentIndex]}</b><span>{matrix.y} {matrix.now[1]} · {matrix.x} {matrix.now[0]}</span></div><button onClick={()=>setRecordOpen(!recordOpen)}>View record</button></div>{recordOpen&&<div className="record-drawer-inline"><header><b>Current record</b><span>{new Date().toLocaleDateString('en-GB')}</span></header>{matrix.hasNow?<dl><div><dt>{matrix.y}</dt><dd>{matrix.now[1]}</dd></div><div><dt>{matrix.x}</dt><dd>{matrix.now[0]}</dd></div><div><dt>Classification</dt><dd>{matrix.states[currentIndex]}</dd></div></dl>:<div className="no-readiness-data">No valid data for this date.</div>}</div>}<ContributionCalendar palette={matrix.palette}/></article>}
function Marker({value,point,actual=false,available=true}){return <b className={`marker-v1 ${actual?'actual':''} ${available?'':'no-data'}`} style={{left:`${point[0]}%`,bottom:`${point[1]}%`}} title={available?`${value} record available`:`${value} has no valid data`}>{value}</b>}
function ContributionCalendar({palette}){const[windowDays,setWindowDays]=useState(365);const days=Array.from({length:windowDays},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(windowDays-1-i));const recorded=i%9!==0&&i%17!==0;return{date:d,color:recorded?palette[(i*7)%palette.length]:null}});const leading=(days[0].date.getDay()+6)%7;const padded=[...Array.from({length:leading},()=>null),...days];const weeks=[];for(let i=0;i<padded.length;i+=7)weeks.push(padded.slice(i,i+7));const labels=weeks.map((week,index)=>{const current=week.find(Boolean)?.date;const previous=weeks[index-1]?.find(Boolean)?.date;return current&&(index===0||previous?.getMonth()!==current.getMonth())?new Intl.DateTimeFormat('en-GB',{month:'short'}).format(current):''});return <section className="history-calendar-v3"><header><div><small>HISTORICAL CLASSIFICATION</small><h4>Daily bivariate states</h4></div><div className="history-range"><button className={windowDays===90?'active':''} onClick={()=>setWindowDays(90)}>90D</button><button className={windowDays===180?'active':''} onClick={()=>setWindowDays(180)}>6M</button><button className={windowDays===365?'active':''} onClick={()=>setWindowDays(365)}>1Y</button></div></header><div className="github-calendar-v3" style={{'--weeks':weeks.length}}><div className="github-months-v3">{labels.map((label,i)=><span key={i}>{label}</span>)}</div><div className="github-body-v3"><div className="github-days-v3"><span>Mon</span><span>Wed</span><span>Fri</span></div><div className="github-weeks-v3">{weeks.map((week,w)=><div className="github-week-v3" key={w}>{week.map((day,i)=>day?<i key={i} className={!day.color?'no-data':''} style={{background:day.color||'#3a403d'}} title={`${new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(day.date)} · ${day.color?'Recorded classification':'No data available'}`}/>:<i className="spacer" key={i}/>)}</div>)}</div></div></div><div className="legend-v3"><span>No data</span><i className="no-data"/><span>Recorded states</span>{[palette[0],palette[2],palette[5],palette[8]].map(color=><i key={color} style={{background:color}}/>)}</div></section>}

function GlanceSection({config,metrics,fasting,habits,workouts}){const items=[
 config.sleep&&{id:'sleep',icon:Moon,label:'Sleep',value:`${metrics.find(x=>x.id==='sleep').value} h`,status:'Health metric',color:'#8b5cf6'},
 config.steps&&{id:'steps',icon:Footprints,label:'Steps',value:metrics.find(x=>x.id==='steps').value.toLocaleString(),status:'Health metric',color:'#38d38b'},
 config.fasting&&{id:'fasting',icon:Flame,label:'Fasting',value:fasting?`${((Date.now()-new Date(fasting.started_at))/36e5).toFixed(1)} h`:'Not active',status:'Fasting tab',color:'#f58b42'},
 config.habits&&{id:'habits',icon:Target,label:'Habits',value:`${habits.filter(x=>x.completed).length}/${Math.max(4,habits.length)}`,status:'Habits tab',color:'#f1c34d'},
 config.workout&&{id:'workout',icon:Dumbbell,label:'Workout',value:workouts[0]?`${workouts[0].duration_minutes} min`:'Not logged',status:'Exercises tab',color:'#38bdf8'},
 config.rhr&&{id:'rhr',icon:HeartPulse,label:'RHR',value:`${metrics.find(x=>x.id==='rhr').value} bpm`,status:'Health metric',color:'#ef6f7d'}
 ].filter(Boolean);return <section className="snapshot-card"><header><h3>Today at a glance</h3><span>Mapped source values</span></header><div className="glance-grid">{items.map(Item=>{const Icon=Item.icon;return <article key={Item.id} style={{'--c':Item.color}}><Icon/><small>{Item.label}</small><b>{Item.value}</b><p>{Item.status}</p></article>})}</div></section>}
function HealthSection({metrics}){const[period,setPeriod]=useState('7D');return <section className="snapshot-card"><header><h3>Health metrics</h3><div className="period-toggle"><button className={period==='7D'?'active':''} onClick={()=>setPeriod('7D')}>7D</button><button className={period==='30D'?'active':''} onClick={()=>setPeriod('30D')}>30D</button></div></header><div className="snapshot-metrics">{metrics.map(metric=><MetricChartCard key={metric.id} metric={metric} period={period}/>)}</div></section>}
function MetricChartCard({metric,period}){const data=metricSeries(metric,period);return <article style={{'--c':metric.color}}><header><span>{metric.label}</span><b>{metric.value.toLocaleString()} {metric.unit}</b></header><ResponsiveContainer width="100%" height={125}><LineChart data={data} margin={{top:8,right:8,bottom:25,left:3}}><CartesianGrid stroke="var(--line)" strokeDasharray="3 4" vertical={false}/><XAxis dataKey="label" tick={{fill:'var(--muted)',fontSize:8}} interval="preserveStartEnd" label={{value:'Time',position:'insideBottom',offset:-15,fill:'var(--muted)',fontSize:8}}/><YAxis width={44} tick={{fill:'var(--muted)',fontSize:8}} label={{value:metric.unit,angle:-90,position:'insideLeft',fill:'var(--muted)',fontSize:8}}/><Tooltip contentStyle={{background:'#07110e',border:'1px solid var(--line)'}} formatter={v=>[`${v} ${metric.unit}`,metric.label]}/>{Array.isArray(metric.target)?<ReferenceArea y1={metric.target[0]} y2={metric.target[1]} fill={metric.color} fillOpacity={.12}/>:<ReferenceLine y={metric.target} stroke={metric.color} strokeDasharray="4 4"/>}<Line dataKey="value" stroke={metric.color} strokeWidth={1.8} dot={{r:2}} connectNulls={false}/></LineChart></ResponsiveContainer><footer><span>Baseline / target</span><b>{Array.isArray(metric.target)?`${metric.target[0]}–${metric.target[1]} ${metric.unit}`:`${metric.target.toLocaleString()} ${metric.unit}`}</b></footer></article>}
function formatElapsed(hours){const total=Math.max(0,Math.floor(hours*60));const days=Math.floor(total/1440);const remaining=total%1440;const h=Math.floor(remaining/60);const m=remaining%60;if(days)return`${days}d ${h}h ${m}m`;if(h)return`${h}h ${m}m`;return`${m}m`}
function FastSection({fast}){if(!fast)return <section className="snapshot-card"><header><h3>Active fast</h3><span>Synced from Fasting</span></header><div className="no-active-fast"><Timer/><div><b>No fast in progress</b><p>Start a fast from the Fasting tab.</p></div></div></section>;const hours=(Date.now()-new Date(fast.started_at))/36e5;const target=fast.target_hours||16;const stage=hours<4?'Fed state':hours<12?'Glycogen phase':hours<18?'Metabolic switch':hours<24?'Fat-burning estimate':'Extended fast';return <section className="snapshot-card"><header><h3>Active fast</h3><span>Synced from Fasting</span></header><div className="active-fast-snapshot"><div className="fast-progress" style={{'--p':`${Math.min(100,hours/target*100)*3.6}deg`}}><b>{hours<10?hours.toFixed(1):Math.floor(hours)}</b><small>hours</small></div><div className="fast-copy"><small>CURRENT ESTIMATED STAGE</small><h3>{stage}</h3><dl><div><dt>Elapsed</dt><dd>{formatElapsed(hours)}</dd></div><div><dt>Goal</dt><dd>{formatElapsed(target)}</dd></div><div><dt>Remaining</dt><dd>{formatElapsed(Math.max(0,target-hours))}</dd></div><div><dt>Expected end</dt><dd>{new Date(fast.expected_end_at).toLocaleString('en-GB')}</dd></div></dl></div></div></section>}
function TimelineSection({rows}){const icon={Habit:Check,Grateful:BookHeart,Sports:Bike,Workout:Dumbbell,Fasting:Flame,Health:HeartPulse};return <section className="snapshot-card"><header><h3>Today’s timeline</h3><span>Synced from Log History</span></header>{rows.length===0?<div className="empty-timeline">No entries recorded today.</div>:<div className="timeline-v1">{rows.slice(0,8).map(row=>{const Icon=icon[row.type]||Activity;return <article key={row.id}><span className={`timeline-icon ${String(row.type).toLowerCase()}`}><Icon/></span><div><small>{row.time||'—'} · {row.type}</small><b>{row.title}</b><p>{row.summary}</p></div></article>})}</div>}</section>}
function SnapshotSettings({visible,setVisible,glance,setGlance,onClose}){return <div className="snapshot-layer"><button className="snapshot-backdrop" onClick={onClose}/><aside className="snapshot-settings"><button className="close" onClick={onClose}><X/></button><small>SNAPSHOT SETTINGS</small><h2>Choose what appears</h2><h3>Widgets</h3>{Object.entries(WIDGETS).map(([id,label])=><label key={id}><span>{visible[id]?<Eye/>:<EyeOff/>}{label}</span><input type="checkbox" checked={visible[id]} onChange={e=>setVisible({...visible,[id]:e.target.checked})}/></label>)}<h3>Today at a glance</h3>{Object.keys(glance).map(id=><label key={id}><span>{id[0].toUpperCase()+id.slice(1)}</span><input type="checkbox" checked={glance[id]} onChange={e=>setGlance({...glance,[id]:e.target.checked})}/></label>)}</aside></div>}
