import { useEffect, useMemo, useState } from 'react'
import { Activity, ChevronLeft, ChevronRight, Droplets, HeartPulse, Scale, Utensils } from 'lucide-react'
import { nutritionRepository } from '../../data/repositories/nutritionRepository'
import { readingsForMetric } from '../fasting/fastingNutritionStore'
import { aggregateMetricForDate, aggregateMetricReadings, metricDecimals, readingDate } from '../health/metricAggregation'
import './NutritionMetabolic.css'

const META = { glucose:['Glucose','#35d483',Droplets], rhr:['RHR','#a66be8',HeartPulse], weight:['Weight','#54aaf5',Scale], hba1c:['HbA1c','#c66be8',Activity] }
const localKey = date => [date.getFullYear(), String(date.getMonth()+1).padStart(2,'0'), String(date.getDate()).padStart(2,'0')].join('-')
function monthGrid(month){const first=new Date(month.getFullYear(),month.getMonth(),1),start=new Date(first);start.setDate(1-((first.getDay()+6)%7));return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})}
function plotPoints(buckets){if(!buckets.length)return'';const values=buckets.map(x=>x.average),lo=Math.min(...values),hi=Math.max(...values),span=hi-lo||1;return buckets.map((x,i)=>`${buckets.length===1?250:i/(buckets.length-1)*500},${130-(x.average-lo)/span*110}`).join(' ')}

export default function NutritionMetabolic(){
 const today=new Date(),[month,setMonth]=useState(new Date(today.getFullYear(),today.getMonth(),1)),[selected,setSelected]=useState(localKey(today)),[nutrition,setNutrition]=useState([]),[token,setToken]=useState(0)
 useEffect(()=>{nutritionRepository.list().then(setNutrition);const refresh=()=>setToken(x=>x+1);window.addEventListener('fitlife:health-readings-changed',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('fitlife:health-readings-changed',refresh);window.removeEventListener('storage',refresh)}},[])
 const raw=useMemo(()=>Object.fromEntries(Object.keys(META).map(metric=>[metric,readingsForMetric(metric)])),[token])
 return <section className="nutrition-metabolic"><header><div><small>METABOLIC</small><h2>Nutrition and linked health readings</h2><p>Calendar indicators use raw records. Summary cards and charts use averages while preserving every reading.</p></div></header>
 <div className="metabolic-layout"><section className="metabolic-calendar"><header><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></button><h3>{new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric'}).format(month)}</h3><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></button></header><div className="weekdays">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=><span key={x}>{x}</span>)}</div><div className="month-grid">{monthGrid(month).map(date=>{const key=localKey(date),hasNutrition=nutrition.some(x=>x.record_date===key),metrics=Object.keys(META).filter(metric=>raw[metric].some(row=>readingDate(row)===key));return <button className={`${selected===key?'selected':''} ${date.getMonth()!==month.getMonth()?'outside':''}`} onClick={()=>setSelected(key)} key={key}><b>{date.getDate()}</b><span>{hasNutrition&&<i className="nutrition-dot"/>}{metrics.map(metric=><i style={{background:META[metric][1]}} key={metric}/>)}</span></button>})}</div><footer><span><i className="nutrition-dot"/>Nutrition</span>{Object.entries(META).map(([metric,[label,color]])=><span key={metric}><i style={{background:color}}/>{label}</span>)}</footer></section>
 <section className="selected-summary"><h3>{selected}</h3><NutritionSummary row={nutrition.find(x=>x.record_date===selected)}/>{Object.entries(META).map(([metric,info])=><SelectedMetric metric={metric} info={info} model={aggregateMetricForDate(raw[metric],metric,selected)} key={metric}/>)}</section></div>
 <div className="metabolic-graphs">{Object.entries(META).map(([metric,info])=><Graph metric={metric} info={info} model={aggregateMetricReadings(raw[metric],metric,'30D')} key={metric}/>)}</div></section>
}
function NutritionSummary({row}){return <article><Utensils/><div><small>NUTRITION</small><b>{row?`${Number(row.calories||0).toLocaleString()} kcal`:'No record'}</b></div></article>}
function SelectedMetric({metric,info,model}){const Icon=info[2],summary=model.summary,decimals=metricDecimals(metric,model.unit);return <article><Icon style={{color:info[1]}}/><div><small>{info[0].toUpperCase()} DAILY AVERAGE</small><b>{summary?`${summary.average.toFixed(decimals)} ${model.unit}`:'No reading'}</b>{summary&&<em>{summary.minimum.toFixed(decimals)}–{summary.maximum.toFixed(decimals)} · {summary.count} readings</em>}</div></article>}
function Graph({metric,info,model}){const Icon=info[2],summary=model.summary,decimals=metricDecimals(metric,model.unit);return <article className="metabolic-graph" style={{'--c':info[1]}}><header><div><Icon/><b>{info[0]}</b></div><span>{model.bucketLabel}</span></header>{summary?<><div className="metabolic-graph-summary"><b>{summary.average.toFixed(decimals)} {model.unit}</b><span>Range {summary.minimum.toFixed(decimals)}–{summary.maximum.toFixed(decimals)} · {summary.count} readings</span></div><svg viewBox="0 0 500 145" preserveAspectRatio="none"><line x1="0"y1="40"x2="500"y2="40"/><line x1="0"y1="90"x2="500"y2="90"/><polyline points={plotPoints(model.buckets)}/></svg></>:<div className="metabolic-graph-empty">No saved readings</div>}<button onClick={()=>{sessionStorage.setItem('fitlife-health-prefill',JSON.stringify({metric}));const nav=document.querySelector('.app nav button[title="Health Metrics"]')||document.querySelector('.app nav button[title="Health"]');nav?nav.click():location.hash='health'}}>Open in Health</button></article>}
