import { useEffect,useMemo,useState } from 'react'
import { CalendarDays,Edit3,Flame,Pause,Play,Plus,Timer,Trash2,X } from 'lucide-react'
import './FastingPage.css'
const KEY='fitlife-fasting-sessions',PROTOCOLS=[['12:12',12],['14:10',14],['16:8',16],['18:6',18],['20:4',20],['OMAD',23],['36h',36],['48h',48],['72h',72]]
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}}
const write=v=>{localStorage.setItem(KEY,JSON.stringify(v));window.dispatchEvent(new CustomEvent('fitlife:fasting-changed',{detail:v}))}
const fmt=ms=>{const s=Math.max(0,Math.floor(ms/1000));return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
const stage=h=>h<4?['Fed state','#d88ca6']:h<12?['Glycogen phase','#df9c50']:h<18?['Metabolic switch estimate','#42cbb8']:h<24?['Fat-adaptation estimate','#7788d9']:['Extended fasting estimate','#a683db']
export default function FastingPage(){const[sessions,setSessions]=useState(read()),[now,setNow]=useState(Date.now()),[editor,setEditor]=useState(null);useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);const active=sessions.find(x=>x.status==='active');const elapsed=active?(now-new Date(active.started_at).getTime())/36e5:0;const [stageName,stageColor]=stage(elapsed);function save(row){let next=[{...row,id:row.id||crypto.randomUUID()},...sessions.filter(x=>x.id!==row.id)];write(next);setSessions(next);setEditor(null)}function start(name,hours){const start=new Date();save({protocol:name,target_hours:hours,started_at:start.toISOString(),expected_end_at:new Date(start.getTime()+hours*36e5).toISOString(),status:'active'})}function end(){save({...active,ended_at:new Date().toISOString(),status:'completed',actual_hours:elapsed})}return <section className="fasting-page"><div className="fasting-heading"><div><small>FASTING</small><h2>Fasting</h2><p>Plan, edit, and synchronise timestamp-based fasts.</p></div><button onClick={()=>setEditor({mode:'new'})}><Plus/>Custom fast</button></div>{active?<article className="active-fast" style={{'--stage':stageColor}}><div className="fast-ring"><strong>{fmt(now-new Date(active.started_at).getTime())}</strong><small>of {active.target_hours} hours</small></div><div><span className="fast-stage"><Flame/>{stageName}</span><h3>{active.protocol}</h3><p>Started {new Date(active.started_at).toLocaleString()}</p><p>Expected end {new Date(active.expected_end_at).toLocaleString()}</p><button onClick={()=>setEditor({mode:'edit',session:active})}><Edit3/>Edit time</button><button className="end-fast" onClick={end}><Pause/>End fast</button></div></article>:<div className="protocols">{PROTOCOLS.map(([name,hours])=><button key={name} onClick={()=>start(name,hours)}><Timer/><b>{name}</b><span>{hours} hours</span><Play/></button>)}</div>}<div className="fasting-grid"><article><h3>History</h3>{sessions.filter(x=>x.status==='completed').slice(0,8).map(x=><button key={x.id} onClick={()=>setEditor({mode:'edit',session:x})}><span>{new Date(x.started_at).toLocaleDateString()}</span><b>{(x.actual_hours||x.target_hours).toFixed(1)}h</b><i>{x.protocol}</i></button>)}</article><article><h3>Calendar</h3><div className="fast-heat">{Array.from({length:84},(_,i)=><i key={i} className={i%9===0?'empty':i%5===0?'exceeded':i%3===0?'complete':'partial'}/>)}</div></article><article><h3>Analytics</h3><b className="fast-stat">{sessions.filter(x=>x.status==='completed').length}</b><p>Completed fasts</p><b className="fast-stat">{Math.max(0,...sessions.map(x=>x.actual_hours||0)).toFixed(1)}h</b><p>Longest fast</p></article></div>{editor&&<FastEditor state={editor} onClose={()=>setEditor(null)} onSave={save}/>}</section>}
function FastEditor({state,onClose,onSave}){const s=state.session;const[start,setStart]=useState(s?.started_at?.slice(0,16)||new Date().toISOString().slice(0,16)),[hours,setHours]=useState(s?.target_hours||16),[protocol,setProtocol]=useState(s?.protocol||'Custom');const expected=new Date(new Date(start).getTime()+Number(hours)*36e5);return <div className="fast-layer"><button className="fast-backdrop" onClick={onClose}/><aside className="fast-drawer"><button className="close" onClick={onClose}><X/></button><small>{state.mode==='edit'?'EDIT FAST':'CUSTOM FAST'}</small><h2>{protocol}</h2><label>Protocol<input value={protocol} onChange={e=>setProtocol(e.target.value)}/></label><label>Start date and time<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Target hours<input type="number" step=".5" value={hours} onChange={e=>setHours(e.target.value)}/></label><p>Expected end: {expected.toLocaleString()}</p><button className="save" onClick={()=>onSave({...s,protocol,target_hours:Number(hours),started_at:new Date(start).toISOString(),expected_end_at:expected.toISOString(),status:s?.status||'active'})}>Save fast</button></aside></div>}
