import {useEffect,useMemo,useState} from 'react'
import {BarChart3,Check,ChevronRight,Cloud,Database,Download,FileJson,LayoutDashboard,LockKeyhole,LogOut,Monitor,Palette,Plug,RefreshCw,Save,Shield,Smartphone,Target,Tablet,Trash2,UserRound,Utensils} from 'lucide-react'
import {supabase} from '../../lib/supabaseClient'
import {profileRepository} from '../../data/repositories/profileRepository'
import './SettingsPage.css'

const MAIN_TABS=[
 ['profile','Profile',UserRound],['goals','Goals',Target],['nutrition','Nutrition',Utensils],['sources','Data Sources',Plug],
 ['themes','Themes',Palette],['dashboard','Dashboard',LayoutDashboard],['analytics','Analytics',BarChart3],['data','Data Management',Database],['privacy','Privacy & Account',Shield]
]
const PROFILE_SECTIONS=[['personal','Personal'],['physical','Physical'],['lifestyle','Lifestyle'],['context','Health Context']]
const TIMEZONES=[
 ['Etc/GMT+12','UTC-12','International Date Line West'],['Pacific/Pago_Pago','UTC-11','Pago Pago'],['Pacific/Honolulu','UTC-10','Honolulu'],
 ['America/Anchorage','UTC-9','Alaska'],['America/Los_Angeles','UTC-8/-7','Los Angeles'],['America/Denver','UTC-7/-6','Denver'],
 ['America/Chicago','UTC-6/-5','Chicago'],['America/New_York','UTC-5/-4','New York'],['America/Halifax','UTC-4/-3','Halifax'],
 ['America/St_Johns','UTC-3:30/-2:30','St John’s'],['America/Sao_Paulo','UTC-3','São Paulo'],['Atlantic/South_Georgia','UTC-2','South Georgia'],
 ['Atlantic/Azores','UTC-1/+0','Azores'],['UTC','UTC+0','Universal Time'],['Europe/London','UTC+0/+1','London'],
 ['Europe/Paris','UTC+1/+2','Central Europe'],['Europe/Helsinki','UTC+2/+3','Eastern Europe'],['Europe/Istanbul','UTC+3','Istanbul'],
 ['Asia/Dubai','UTC+4','Dubai'],['Asia/Kabul','UTC+4:30','Kabul'],['Asia/Karachi','UTC+5','Karachi'],['Asia/Kolkata','UTC+5:30','India'],
 ['Asia/Kathmandu','UTC+5:45','Kathmandu'],['Asia/Dhaka','UTC+6','Dhaka'],['Asia/Yangon','UTC+6:30','Yangon'],['Asia/Bangkok','UTC+7','Bangkok'],
 ['Asia/Manila','UTC+8','Manila'],['Asia/Tokyo','UTC+9','Tokyo'],['Australia/Adelaide','UTC+9:30/+10:30','Adelaide'],
 ['Australia/Sydney','UTC+10/+11','Sydney'],['Pacific/Noumea','UTC+11','Nouméa'],['Pacific/Auckland','UTC+12/+13','Auckland'],
 ['Pacific/Chatham','UTC+12:45/+13:45','Chatham'],['Pacific/Apia','UTC+13','Apia'],['Pacific/Kiritimati','UTC+14','Kiritimati']
]
const LOCALES=[['en-GB','English (United Kingdom)'],['en-US','English (United States)'],['en-PH','English (Philippines)'],['fr-FR','Français (France)'],['de-DE','Deutsch (Deutschland)'],['es-ES','Español (España)'],['it-IT','Italiano (Italia)'],['pt-BR','Português (Brasil)'],['ja-JP','日本語'],['en-AU','English (Australia)']]
const ACTIVITY=[['sedentary','Sedentary','Mostly seated; little structured activity'],['light','Lightly active','Light activity 1–3 days weekly'],['moderate','Moderately active','Training or activity 3–5 days weekly'],['very','Very active','Hard activity 6–7 days weekly'],['athlete','Athlete','High-volume or performance training']]
const DIETS=['Balanced','High protein','Mediterranean','Low carbohydrate','Ketogenic','Vegetarian','Vegan','Pescatarian','Carnivore','Custom']
const FASTING=['Never fasted','Beginner','Occasional faster','Regular faster','Experienced faster','Advanced multi-day faster']
const ALLERGIES=['Milk / lactose','Eggs','Peanuts','Tree nuts','Gluten / wheat','Soy','Fish','Shellfish','Sesame']
const THEMES=[
 ['forest','Forest',['#08120d','#121e18','#54d982']],['ocean','Ocean',['#07131d','#0e2534','#38bdf8']],['midnight','Midnight',['#070816','#15172d','#818cf8']],
 ['sunrise','Sunrise',['#1d1009','#322015','#fb923c']],['nordic','Nordic',['#0f172a','#1e293b','#38bdf8']],['sakura','Sakura',['#1d0c18','#321426','#f472b6']],
 ['emerald','Emerald Gold',['#07110d','#10231a','#e5b94b']],['earth','Earth',['#18120e','#2a211a','#c58b5a']]
]
const defaults={display_name:'',date_of_birth:'',timezone:'Europe/London',locale:'en-GB',locale_auto:true,measurement_system:'metric',height_unit:'cm',weight_unit:'kg',distance_unit:'km',glucose_unit:'mg/dL',week_starts_on:1,clock_format:'24h',height_cm:'',activity_level:'moderate',target_weight_kg:'',active_calorie_goal:'',primary_goals:[],health_considerations:'',medication_notes:'',mobility_notes:'',dietary_pattern:'Balanced',allergies_enabled:false,allergy_items:[],fasting_experience:'Beginner',sleep_start:'',sleep_end:'',meal_schedule:'',theme_id:'forest',theme_mode:'dark',dashboard_preferences:{density:'comfortable',cardStyle:'elevated',device:'desktop'},calorie_target:'',protein_target_g:'',carbohydrate_target_g:'',fat_target_g:'',fibre_target_g:'',water_target_ml:'',analysis_settings:{minimumMatchedDays:7,minimumObservations:7,outlierHandling:'flag',incompleteNutrition:'exclude',estimatedValues:'flag',baselineDays:30,qualityThreshold:'limited'}}
function suggestedLocale(zone){if(zone.startsWith('America/'))return'en-US';if(zone==='Asia/Manila')return'en-PH';if(zone.startsWith('Australia/'))return'en-AU';if(zone==='Europe/Paris')return'fr-FR';if(zone==='Europe/Berlin')return'de-DE';if(zone==='Asia/Tokyo')return'ja-JP';return'en-GB'}
const num=v=>v===''||v==null?null:Number(v)
export default function SettingsPage(){
 const[tab,setTab]=useState('profile'),[profileSection,setProfileSection]=useState('personal'),[form,setForm]=useState(defaults),[busy,setBusy]=useState(true),[message,setMessage]=useState(''),[customAllergy,setCustomAllergy]=useState('')
 useEffect(()=>{profileRepository.get().then(row=>row&&setForm({...defaults,...row,analysis_settings:{...defaults.analysis_settings,...row.analysis_settings},allergy_items:row.allergy_items||[]})).catch(e=>setMessage(e.message)).finally(()=>setBusy(false));return profileRepository.subscribe(()=>profileRepository.get().then(row=>row&&setForm(current=>({...current,...row}))))},[])
 const selectedZone=useMemo(()=>TIMEZONES.find(x=>x[0]===form.timezone),[form.timezone])
 function update(key,value){setForm(current=>({...current,[key]:value}))}
 function changeTimezone(zone){setForm(current=>({...current,timezone:zone,locale:current.locale_auto?suggestedLocale(zone):current.locale}))}
 function toggleAllergy(item){update('allergy_items',form.allergy_items.includes(item)?form.allergy_items.filter(x=>x!==item):[...form.allergy_items,item])}
 function emitTheme(theme=form.theme_id,mode=form.theme_mode){localStorage.setItem('theme',theme);localStorage.setItem('themeMode',mode);window.dispatchEvent(new CustomEvent('fitlife:theme-changed',{detail:{theme,mode}}))}
 function chooseTheme(id){update('theme_id',id);emitTheme(id,form.theme_mode)}
 function chooseMode(mode){update('theme_mode',mode);emitTheme(form.theme_id,mode)}
 async function save(){setBusy(true);setMessage('');try{const row=await profileRepository.save({...form,height_cm:num(form.height_cm),target_weight_kg:num(form.target_weight_kg),active_calorie_goal:num(form.active_calorie_goal),calorie_target:num(form.calorie_target),protein_target_g:num(form.protein_target_g),carbohydrate_target_g:num(form.carbohydrate_target_g),fat_target_g:num(form.fat_target_g),fibre_target_g:num(form.fibre_target_g),water_target_ml:num(form.water_target_ml)});setForm({...defaults,...row,analysis_settings:{...defaults.analysis_settings,...row.analysis_settings}});emitTheme(row.theme_id||'forest',row.theme_mode||'dark');setMessage('Settings saved and synchronised across devices.')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="settings-v2"><header className="settings-heading"><div><small>FITLIFE SETTINGS</small><h2>Settings</h2><p>Update only the area you need. Changes are saved to your FitLife profile.</p></div><button className="settings-save" onClick={save} disabled={busy}><Save/>{busy?'Saving...':'Save changes'}</button></header>{message&&<div className="settings-message">{message}</div>}
 <div className="settings-shell"><nav className="settings-main-tabs" aria-label="Settings sections">{MAIN_TABS.map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon/><span>{label}</span><ChevronRight/></button>)}</nav><main className="settings-content">
 {tab==='profile'&&<div className="profile-settings"><div className="profile-toggle"><small>PROFILE AREA</small>{PROFILE_SECTIONS.map(([id,label])=><button className={profileSection===id?'active':''} onClick={()=>setProfileSection(id)} key={id}>{label}</button>)}</div><section className="settings-panel">{profileSection==='personal'&&<><PanelTitle title="Personal" text="Identity, local time and calendar behaviour."/><div className="settings-fields"><Field label="Display name"><input value={form.display_name||''} onChange={e=>update('display_name',e.target.value)}/></Field><Field label="Date of birth"><input type="date" value={form.date_of_birth||''} onChange={e=>update('date_of_birth',e.target.value)}/></Field><Field label="Timezone" wide><select value={form.timezone} onChange={e=>changeTimezone(e.target.value)}>{TIMEZONES.map(([id,offset,place])=><option value={id} key={id}>{offset} · {place} · {id}</option>)}</select><small>{selectedZone?`${selectedZone[1]} currently selected. Regional zones automatically handle seasonal clock changes.`:''}</small></Field><div className="setting-switch wide"><div><b>Automatic locale</b><span>Suggest date and number formatting from the selected timezone.</span></div><button className={form.locale_auto?'on':''} role="switch" aria-checked={form.locale_auto} onClick={()=>{const next=!form.locale_auto;setForm(x=>({...x,locale_auto:next,locale:next?suggestedLocale(x.timezone):x.locale}))}}><i/></button></div><Field label="Locale" wide><select disabled={form.locale_auto} value={form.locale} onChange={e=>update('locale',e.target.value)}>{LOCALES.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></Field><Field label="Week starts"><select value={form.week_starts_on} onChange={e=>update('week_starts_on',Number(e.target.value))}><option value="1">Monday</option><option value="0">Sunday</option></select></Field><Field label="Clock format"><select value={form.clock_format} onChange={e=>update('clock_format',e.target.value)}><option value="24h">24 hour</option><option value="12h">12 hour</option></select></Field></div></>}
 {profileSection==='physical'&&<><PanelTitle title="Physical and units" text="Measurement preferences used throughout FitLife."/><div className="settings-fields"><Field label="Height"><input type="number" min="0" value={form.height_cm??''} onChange={e=>update('height_cm',e.target.value)}/></Field><Field label="Measurement system"><select value={form.measurement_system} onChange={e=>update('measurement_system',e.target.value)}><option value="metric">Metric</option><option value="imperial">Imperial</option></select></Field><Field label="Height unit"><select value={form.height_unit} onChange={e=>update('height_unit',e.target.value)}><option>cm</option><option>ft/in</option></select></Field><Field label="Weight unit"><select value={form.weight_unit} onChange={e=>update('weight_unit',e.target.value)}><option>kg</option><option>lb</option></select></Field><Field label="Distance unit"><select value={form.distance_unit} onChange={e=>update('distance_unit',e.target.value)}><option>km</option><option>mi</option></select></Field><Field label="Glucose unit"><select value={form.glucose_unit} onChange={e=>update('glucose_unit',e.target.value)}><option>mg/dL</option><option>mmol/L</option></select></Field></div></>}
 {profileSection==='lifestyle'&&<><PanelTitle title="Lifestyle" text="Optional context for goals and descriptive analytics."/><div className="settings-fields"><Field label="Activity level" wide><select value={form.activity_level||''} onChange={e=>update('activity_level',e.target.value)}>{ACTIVITY.map(([id,label,help])=><option value={id} key={id}>{label} · {help}</option>)}</select></Field><Field label="Dietary pattern" wide><select value={form.dietary_pattern||''} onChange={e=>update('dietary_pattern',e.target.value)}>{DIETS.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Fasting experience" wide><select value={form.fasting_experience||''} onChange={e=>update('fasting_experience',e.target.value)}>{FASTING.map(x=><option key={x}>{x}</option>)}</select></Field><div className="setting-switch wide"><div><b>Allergies and intolerances</b><span>Enable only when you want these details included in your profile.</span></div><button className={form.allergies_enabled?'on':''} role="switch" aria-checked={form.allergies_enabled} onClick={()=>update('allergies_enabled',!form.allergies_enabled)}><i/></button></div>{form.allergies_enabled&&<div className="allergy-picker wide"><div>{ALLERGIES.map(item=><button className={form.allergy_items.includes(item)?'selected':''} onClick={()=>toggleAllergy(item)} key={item}>{form.allergy_items.includes(item)&&<Check/>}{item}</button>)}</div><label><input value={customAllergy} onChange={e=>setCustomAllergy(e.target.value)} placeholder="Add another allergy or intolerance"/><button disabled={!customAllergy.trim()} onClick={()=>{const item=customAllergy.trim();if(item&&!form.allergy_items.includes(item))update('allergy_items',[...form.allergy_items,item]);setCustomAllergy('')}}>Add</button></label>{form.allergy_items.filter(x=>!ALLERGIES.includes(x)).map(item=><button className="custom-chip" onClick={()=>toggleAllergy(item)} key={item}>{item} ×</button>)}</div>}</div></>}
 {profileSection==='context'&&<><PanelTitle title="Health context" text="Optional private notes. These do not replace professional medical records."/><div className="settings-fields"><Field label="Health considerations" wide><textarea value={form.health_considerations||''} onChange={e=>update('health_considerations',e.target.value)}/></Field><Field label="Medication notes" wide><textarea value={form.medication_notes||''} onChange={e=>update('medication_notes',e.target.value)}/></Field><Field label="Injury or mobility considerations" wide><textarea value={form.mobility_notes||''} onChange={e=>update('mobility_notes',e.target.value)}/></Field><Field label="Typical sleep start"><input type="time" value={form.sleep_start||''} onChange={e=>update('sleep_start',e.target.value)}/></Field><Field label="Typical sleep end"><input type="time" value={form.sleep_end||''} onChange={e=>update('sleep_end',e.target.value)}/></Field></div></>}</section></div>}
 {tab==='goals'&&<section className="settings-panel"><PanelTitle title="Goals" text="Personal targets used by dashboards and summaries."/><div className="settings-fields"><Field label="Target weight"><input type="number" value={form.target_weight_kg??''} onChange={e=>update('target_weight_kg',e.target.value)}/></Field><Field label="Active calorie goal"><input type="number" value={form.active_calorie_goal??''} onChange={e=>update('active_calorie_goal',e.target.value)}/></Field></div></section>}
 {tab==='nutrition'&&<section className="settings-panel"><PanelTitle title="Nutrition targets" text="Defaults shown in the dedicated Nutrition module."/><div className="settings-fields">{[['calorie_target','Calories','kcal'],['protein_target_g','Protein','g'],['carbohydrate_target_g','Carbohydrates','g'],['fat_target_g','Fat','g'],['fibre_target_g','Fibre','g'],['water_target_ml','Water','ml']].map(([k,l,u])=><Field label={`${l} (${u})`} key={k}><input type="number" min="0" value={form[k]??''} onChange={e=>update(k,e.target.value)}/></Field>)}<Field label="Meal schedule" wide><textarea value={form.meal_schedule||''} onChange={e=>update('meal_schedule',e.target.value)}/></Field></div></section>}
 {tab==='themes'&&<section className="settings-panel"><PanelTitle title="Themes" text="Change the complete FitLife colour combination. Preview applies immediately; Save synchronises it."/><div className="mode-picker"><button className={form.theme_mode==='dark'?'selected':''} onClick={()=>chooseMode('dark')}>Dark mode</button><button className={form.theme_mode==='light'?'selected':''} onClick={()=>chooseMode('light')}>Light mode</button><button className={form.theme_mode==='system'?'selected':''} onClick={()=>chooseMode('system')}>Use device</button></div><div className="theme-grid">{THEMES.map(([id,label,colours])=><button className={form.theme_id===id?'selected':''} onClick={()=>chooseTheme(id)} key={id}><div>{colours.map(c=><i style={{background:c}} key={c}/>)}</div><b>{label}</b><span>{form.theme_id===id?<><Check/>Active</>:'Use theme'}</span></button>)}</div></section>}
 {tab==='analytics'&&<section className="settings-panel"><PanelTitle title="Analytics quality" text="Control when FitLife may show a descriptive pattern."/><div className="settings-fields">{[['minimumMatchedDays','Minimum matched days'],['minimumObservations','Minimum observations'],['baselineDays','Baseline period (days)']].map(([k,l])=><Field label={l} key={k}><input type="number" min="1" value={form.analysis_settings[k]} onChange={e=>update('analysis_settings',{...form.analysis_settings,[k]:Number(e.target.value)})}/></Field>)}<Field label="Outlier handling"><select value={form.analysis_settings.outlierHandling} onChange={e=>update('analysis_settings',{...form.analysis_settings,outlierHandling:e.target.value})}><option>flag</option><option>exclude</option><option>include</option></select></Field></div></section>}
 {tab==='sources'&&<DataSourcesPanel/>}
 {tab==='dashboard'&&<DashboardPanel value={form.dashboard_preferences||defaults.dashboard_preferences} onChange={value=>update('dashboard_preferences',value)}/>}
 {tab==='data'&&<DataManagementPanel setMessage={setMessage}/>}
 {tab==='privacy'&&<PrivacyPanel setMessage={setMessage}/>}
 </main></div></section>
}
function PanelTitle({title,text}){return <header className="panel-title"><h3>{title}</h3><p>{text}</p></header>}
function Field({label,wide=false,children}){return <label className={wide?'wide':''}><span>{label}</span>{children}</label>}


function DashboardPanel({value,onChange}){const u=(k,v)=>{const next={...value,[k]:v};onChange(next);localStorage.setItem('fitlife-dashboard-preferences',JSON.stringify(next))};return <section className="settings-panel"><PanelTitle title="Dashboard" text="Choose how Snapshot cards appear on each device. Existing widget layouts remain intact."/><div className="device-choice"><button className={value.device==='desktop'?'selected':''} onClick={()=>u('device','desktop')}><Monitor/>Desktop</button><button className={value.device==='tablet'?'selected':''} onClick={()=>u('device','tablet')}><Tablet/>iPad</button><button className={value.device==='phone'?'selected':''} onClick={()=>u('device','phone')}><Smartphone/>iPhone</button></div><div className="settings-fields"><Field label="Display density"><select value={value.density} onChange={e=>u('density',e.target.value)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option><option value="dense">Dense</option></select></Field><Field label="Card style"><select value={value.cardStyle} onChange={e=>u('cardStyle',e.target.value)}><option value="elevated">Elevated</option><option value="flat">Flat</option><option value="glass">Glass</option></select></Field></div><button className="settings-action primary" onClick={()=>{location.hash='snapshot';window.dispatchEvent(new CustomEvent('fitlife:open-dashboard-editor',{detail:{device:value.device}}))}}><LayoutDashboard/>Open dashboard editor</button><button className="settings-action" onClick={()=>{['desktop','tablet','phone'].forEach(x=>localStorage.removeItem(`fitlife-dashboard-layout-${x}`));window.dispatchEvent(new CustomEvent('fitlife:dashboard-layout-reset'))}}>Reset saved device layouts</button></section>}
function DataSourcesPanel(){return <section className="settings-panel"><PanelTitle title="Data Sources" text="Connection controls will use source priority and import lineage without duplicating canonical records."/><div className="source-list">{[['Garmin Connect','Health, activity and GPS'],['Strava','Activities and exercise details'],['MyFitnessPal','Daily nutrition imports'],['Manual','All supported FitLife records']].map(([name,help],i)=><article key={name}><span>{i+1}</span><div><b>{name}</b><small>{help}</small></div><em>{name==='Manual'?'Available':'Not connected'}</em></article>)}</div></section>}
function download(name,data,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function DataManagementPanel({setMessage}){async function exportCloud(){try{const tables=['fitlife_profiles','fitlife_metric_definitions','fitlife_metric_observations','fitlife_nutrition_days','fitlife_nutrition_targets','fitlife_habits','fitlife_habit_logs','fitlife_fasting_sessions','fitlife_activities','fitlife_activity_media','fitlife_gratitude_entries'];const payload={format:'FitLife Full Backup',version:1,exported_at:new Date().toISOString(),tables:{}};for(const table of tables){const{data,error}=await supabase.from(table).select('*');if(error)throw error;payload.tables[table]=data||[]}download(`fitlife-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(payload,null,2));setMessage('Full FitLife JSON export created.')}catch(e){setMessage(e.message)}}function exportUi(){const data={exported_at:new Date().toISOString(),preferences:Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('fitlife-')||k==='theme'||k==='themeMode').map(k=>[k,localStorage.getItem(k)]))};download('fitlife-ui-preferences.json',JSON.stringify(data,null,2))}async function integrity(){try{const checks={};for(const table of ['fitlife_profiles','fitlife_nutrition_days','fitlife_fasting_sessions','fitlife_activities']){const{count,error}=await supabase.from(table).select('*',{count:'exact',head:true});if(error)throw error;checks[table]=count}setMessage(`Integrity check completed. Profile ${checks.fitlife_profiles}; Nutrition ${checks.fitlife_nutrition_days}; Fasts ${checks.fitlife_fasting_sessions}; Activities ${checks.fitlife_activities}.`)}catch(e){setMessage(e.message)}}return <section className="settings-panel"><PanelTitle title="Data Management" text="Export canonical cloud data, preserve UI preferences, and verify repository access."/><div className="management-grid"><button onClick={exportCloud}><Download/><b>Export full FitLife JSON</b><span>Canonical signed-in records from Supabase</span></button><button onClick={exportUi}><FileJson/><b>Export UI preferences</b><span>Themes and device layouts stored locally</span></button><button onClick={integrity}><RefreshCw/><b>Check data integrity</b><span>Verify canonical tables are reachable</span></button><button onClick={()=>{Object.keys(localStorage).filter(k=>k.startsWith('fitlife-quick-log-')).forEach(k=>localStorage.removeItem(k));setMessage('Temporary Quick Log cache cleared. Canonical records were not touched.')}}><Trash2/><b>Clear temporary cache</b><span>Does not delete cloud records</span></button></div><div className="import-note"><b>Imports</b><p>JSON restore, CSV, Excel, Garmin, Strava, MyFitnessPal and GPX require the validated preview and duplicate-detection pipeline. They remain unavailable here until that repository workflow is installed, preventing accidental duplication.</p></div></section>}
function PrivacyPanel({setMessage}){const[email,setEmail]=useState('');const[confirm,setConfirm]=useState(false);useEffect(()=>{supabase.auth.getUser().then(({data})=>setEmail(data.user?.email||''))},[]);async function reset(){const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/#reset-password`});setMessage(error?error.message:'Password reset email requested.')}async function others(){const{error}=await supabase.auth.signOut({scope:'others'});setMessage(error?error.message:'Other sessions have been signed out.')}async function deletion(){const{data:{user}}=await supabase.auth.getUser();const{error}=await supabase.from('fitlife_account_deletion_requests').insert({user_id:user.id,requested_email:user.email});setMessage(error?error.message:'Account deletion request recorded. Export your data before the request is completed.');setConfirm(false)}return <section className="settings-panel"><PanelTitle title="Privacy & Account" text="Authentication, active sessions and controlled account deletion."/><div className="account-email"><LockKeyhole/><div><small>SIGNED IN EMAIL</small><b>{email||'Loading...'}</b></div></div><button className="settings-action" onClick={reset}>Send password reset email</button><button className="settings-action" onClick={others}>Sign out other devices</button><button className="settings-action" onClick={()=>supabase.auth.signOut().then(()=>location.reload())}><LogOut/>Sign out this device</button><div className="danger-zone"><h3>Danger zone</h3><p>Deletion requests are audited. Export your FitLife data first.</p>{!confirm?<button onClick={()=>setConfirm(true)}>Request account deletion</button>:<div><b>Record an account deletion request?</b><button onClick={()=>setConfirm(false)}>Cancel</button><button className="danger" onClick={deletion}>Request deletion</button></div>}</div></section>}
