import { useMemo, useState } from 'react'
import { Activity, Dumbbell, HeartPulse, Info, Sparkles, Target } from 'lucide-react'
import './AnalyticsPage.css'

const matrices=[
 {id:'health',title:'Health & Recovery',Icon:HeartPulse,x:'Strain',y:'Readiness',now:[76,61],state:'Productive Momentum',color:'#6f92c4',advice:['Proceed with planned activity if the body feels well','Protect sleep and recovery habits','Review consecutive high-strain days'],palette:['#efe7d5','#b8d9c6','#5ca69a','#ddb3bd','#9ca8c7','#6685b2','#b76f83','#745d87','#493d59']},
 {id:'training',title:'Sports & Workouts',Icon:Dumbbell,x:'Intensity',y:'Volume',now:[68,72],state:'Balanced Training Load',color:'#6c67a8',advice:['Maintain the planned session volume','Avoid abrupt intensity increases','Use recovery sessions after hard blocks'],palette:['#eee6cd','#c5d9a7','#69ad7d','#d9b77d','#75aaa8','#477fa5','#bc7554','#7869a7','#424872']},
 {id:'habits',title:'Habits & Mindfulness',Icon:Target,x:'Rest',y:'Consistency',now:[72,82],state:'Sustainable Rhythm',color:'#5e8bb3',advice:['Keep the current routine simple','Protect rest while consistency is high','Use minimum targets on difficult days'],palette:['#ead9df','#c9badd','#8089bd','#d9c8ca','#96bbb5','#6494a5','#add7ba','#68b19d','#566e9c']}
]
function history(matrix,count){return Array.from({length:count},(_,i)=>i%8===0?null:matrix.palette[(i*5)%9])}
export default function AnalyticsPage(){const[view,setView]=useState('health'),[period,setPeriod]=useState('30D');const shown=view==='all'?matrices:matrices.filter(x=>x.id===view);return <section className="analytics-page"><header><div><small>BIVARIATE ANALYTICS</small><h2>Activity Analytics</h2><p>Current classifications, historical records, calculation context, and practical guidance.</p></div><button><Info/>How calculations work</button></header><div className="analytics-toggle">{matrices.map(m=><button className={view===m.id?'active':''} onClick={()=>setView(m.id)} key={m.id}>{m.title}</button>)}<button className={view==='all'?'active':''} onClick={()=>setView('all')}>Show all</button></div><div className="analytics-periods">{['7D','30D','90D','1Y'].map(x=><button className={period===x?'active':''} onClick={()=>setPeriod(x)} key={x}>{x}</button>)}</div><div className={`analytics-content ${view==='all'?'all':''}`}>{shown.map(matrix=><AnalyticsCard matrix={matrix} period={period} key={matrix.id}/>)}</div></section>}
function AnalyticsCard({matrix,period}){const Icon=matrix.Icon;const count=period==='7D'?7:period==='30D'?30:period==='90D'?90:365;const cells=history(matrix,count);return <article className="analytics-card"><header><div><Icon/><span>{matrix.title}</span></div><b style={{background:matrix.color}}>{matrix.state}</b></header><div className="analytics-main"><div className="analytics-diamond"><div>{matrix.palette.map((c,i)=><i style={{background:c}} key={i}/>)}</div><span style={{left:`${matrix.now[0]}%`,bottom:`${matrix.now[1]}%`}}>X</span></div><div className="analytics-advice"><small>CURRENT SCORES</small><div className="analytics-scores"><span><b>{matrix.now[1]}</b>{matrix.y}</span><span><b>{matrix.now[0]}</b>{matrix.x}</span></div><h3>Recommended today</h3>{matrix.advice.map((x,i)=><p key={i}><Sparkles/>{x}</p>)}</div></div><HistoryGrid cells={cells} period={period}/></article>}
function HistoryGrid({cells,period}){if(period==='7D')return <div className="history-seven"><div>{['M','T','W','T','F','S','S'].map((x,i)=><span key={i}>{x}</span>)}</div><div>{cells.map((c,i)=><i className={!c?'empty':''} style={{background:c||'#b8bcba'}} key={i}/>)}</div></div>;if(period==='30D')return <div className="history-thirty">{cells.map((c,i)=><i className={!c?'empty':''} style={{background:c||'#b8bcba'}} title={`Day ${i+1}`} key={i}/>)}</div>;return <div className={`history-github ${period==='1Y'?'year':''}`}>{cells.map((c,i)=><i className={!c?'empty':''} style={{background:c||'#b8bcba'}} key={i}/>)}</div>}
