import{useEffect,useMemo,useState}from'react';import{Activity,BookHeart,CalendarDays,Camera,ChevronRight,Cloud,CloudOff,Dumbbell,Flame,HeartPulse,History,Leaf,Menu,Minus,Plus,Search,Settings,Timer,Trophy,Upload,UserRound,X}from'lucide-react';import{LineChart,Line,ResponsiveContainer,Tooltip}from'recharts';import{exercises,themes,metricSeries}from'./data';
import LogHistoryPage from './features/log-history/LogHistoryPage'
import GratefulPage from './features/grateful/GratefulPage'
import SportsPage from './features/sports/SportsPage'
import HabitsPage from './features/habits/HabitsPage'
import FastingPage from './features/fasting/FastingPage'
import ExercisesPage from './features/exercises/ExercisesPage'
import HealthMetricsPage from './features/health/HealthMetricsPage'
import SnapshotPage from './features/snapshot/SnapshotPage'
import MyLifePage from './features/my-life/MyLifePage'
import NewSettingsPage from './features/settings/SettingsPage'
import SnapshotPageV1 from './features/snapshot/SnapshotPage'

const nav=['Snapshot','My Life','Health Metrics','Exercises','Sports','Habits','Fasting','Log History','Grateful','Settings'];
const keys=['snapshot','life','health','exercises','sports','habits','fasting','history','grateful','settings'];
const palette={health:['#5f8fa8','#8b7185','#d45c66','#48a9b0','#7d8f79','#c68162','#35c7a0','#94bf68','#e4b84f'],training:['#d5ceb8','#c79568','#ee873c','#8e83ac','#a56c79','#d2704f','#6765b5','#995596','#c44779'],habits:['#745a4a','#87999b','#4fc7d5','#af765d','#7d858f','#58a1b6','#dd7952','#8d718b','#5c78af']};
const sector={health:['Passive Recovery','Low Reserve','Systemic Burnout','Active Recovery','Adaptive Balance','Building Fatigue','Peak Prime','Productive Load','Heroic Effort'],training:['Recovery Movement','Technique / Skill','Power Burst','Active Base','Productive Training','HIIT Burst','Aerobic Endurance','Endurance Builder','Peak Overload'],habits:['Disrupted Rhythm','Re-entry Zone','Passive Reset','Habit Strain','Balanced Routine','Gentle Momentum','Running on Fumes','Strong Rhythm','Unstoppable Flow']};
const id=()=>crypto.randomUUID();const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function Matrix({kind,x,y}){const idx=(y<34?0:y<67?3:6)+(x<34?0:x<67?1:2);return <><div className="matrix"><span className="ylabel">{kind==='health'?'Readiness':kind==='training'?'Volume':'Consistency'} ↑</span><div className="nine">{palette[kind].map((c,i)=><button className={i===idx?'active':''} style={{background:c}} key={c} title={sector[kind][i]}><b>{sector[kind][i]}</b>{i===idx&&<i>NOW</i>}</button>)}</div><span className="xlabel">{kind==='health'?'Strain':kind==='training'?'Intensity':'Rest'} →</span><div className="trajectory"><span>○ 30D</span><em>━━━━</em><span>◆ 7D</span><em>━━━━</em><strong>● NOW</strong></div></div><Heat colors={palette[kind]}/></>}
function Heat({colors}){return <div><div className="months"><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep 2026</span></div><div className="heat">{Array.from({length:91},(_,i)=><i key={i} style={{background:i%13===0?'var(--empty)':colors[(i*7+i%4)%9]}} title={i%13===0?'No data':'Daily state'}/>)}</div></div>}
function Biv({kind,title,x,y}){return <article className="card biv"><small>{title}</small><h3>{kind==='health'?'Readiness × Strain':kind==='training'?'Volume × Intensity':'Consistency × Rest'}</h3><Matrix kind={kind} x={x} y={y}/><div className="coverage">Coverage 76% · Log HRV to improve accuracy</div></article>}
function Spark({name,value,unit,color}){const data=metricSeries[name].map((v,i)=>({i,v}));return <article className="sparkcard" style={{'--c':color}}><small>{name}</small><h3>{value} <em>{unit}</em></h3><div><ResponsiveContainer><LineChart data={data}><Line dataKey="v" stroke={color} strokeWidth={2.5} dot={false}/><Tooltip contentStyle={{background:'#111',border:0}}/></LineChart></ResponsiveContainer></div></article>}
function Snapshot(){return <><section className="bivs"><Biv kind="health" title="HEALTH & RECOVERY" x={82} y={73}/><Biv kind="training" title="SPORTS & WORKOUTS" x={61} y={74}/><Biv kind="habits" title="HABITS & MINDFULNESS" x={71} y={66}/></section><Section title="Health metrics" subtitle="Compact favourites with seven-day trends."><div className="sparks"><Spark name="RHR" value="58" unit="bpm" color="#ef6b72"/><Spark name="HRV" value="68" unit="ms" color="#a78bfa"/><Spark name="Steps" value="8,742" unit="" color="#43d17d"/><Spark name="Sleep" value="7h 28m" unit="" color="#4f8ff7"/><Spark name="Weight" value="72.4" unit="kg" color="#43c6cf"/><Spark name="Mood" value="8" unit="/10" color="#e6b94b"/><Spark name="Energy" value="8" unit="/10" color="#f97316"/><Spark name="VO2" value="43.8" unit="" color="#14b8a6"/></div></Section><SportPreview/><div className="three"><Panel icon={<Trophy/>} title="Recent wins"><p>◆ Walking personal best · 64 min</p><p>🔥 Italian lesson · 41-day streak</p></Panel><Panel icon={<Timer/>} title="Active fast"><strong className="big">11h 42m</strong><p>Estimated equivalent 14h 18m</p></Panel><Panel icon={<History/>} title="Today"><p>08:15 · Sleep logged</p><p>09:40 · Fast started</p><p>18:20 · Walking exceeded</p></Panel></div></>}
function Section({title,subtitle,children}){return <section className="section"><h2>{title}</h2><p className="muted">{subtitle}</p>{children}</section>};function Panel({icon,title,children}){return <article className="card"><div className="panelhead">{icon}<h3>{title}</h3></div>{children}</article>}
function SportPreview(){return <Section title="Sports & workouts" subtitle="Recent visual memories and performance."><article className="sporthero"><div><Camera/><b>Cycling</b></div><section><small>Sunday, 6 September 2026</small><h2>Cycling Commute</h2><div className="stats"><b>42 min</b><b>14.6 km</b><b>381 kcal</b><b>142 bpm</b></div></section></article></Section>}
function Health(){const[logs,setLogs]=useState(()=>load('healthLogs',[]));const[name,setName]=useState('RHR'),[value,setValue]=useState('');function add(){if(!value)return;const n=[{id:id(),name,value:+value,date:new Date().toISOString()},...logs];setLogs(n);save('healthLogs',n);setValue('')}return <Page title="Health Metrics" sub="Flexible targets, quick recording and colourful trends."><div className="quick"><select value={name} onChange={e=>setName(e.target.value)}>{['RHR','HRV','Steps','Sleep','Weight','Mood','Energy','VO2','Blood glucose'].map(x=><option>{x}</option>)}</select><input type="number" value={value} onChange={e=>setValue(e.target.value)} placeholder="Value"/><button onClick={add}><Plus/>Save metric</button></div><div className="sparks wide"><Spark name="RHR" value="58" unit="bpm" color="#ef6b72"/><Spark name="HRV" value="68" unit="ms" color="#a78bfa"/><Spark name="Steps" value="8,742" unit="" color="#43d17d"/><Spark name="Sleep" value="7h 28m" unit="" color="#4f8ff7"/></div><List rows={logs.map(x=>[x.name,String(x.value),new Date(x.date).toLocaleString()])}/></Page>}
function Habits(){const[walk,setWalk]=useState(37),[done,setDone]=useState(false);return <Page title="Habits" sub="Quick logging, streak lines, achievements and personal bests."><div className="twocol"><article className="card"><Flame/><h3>Walking</h3><p>Minimum 10 minutes</p><div className="step"><button onClick={()=>setWalk(Math.max(0,walk-5))}><Minus/></button><strong>{walk} min</strong><button onClick={()=>setWalk(walk+5)}><Plus/></button></div><button className="primary" onClick={()=>save('walk',walk)}>Save today</button><p className="good">+{Math.max(0,walk-10)} min beyond target · 18-day streak</p><div className="streak">●━━━━●━━━━★━━━━●━━━━◆</div><Heat colors={palette.habits}/></article><article className="card"><BookHeart/><h3>Morning Italian</h3><p>Binary habit · 41-day streak</p><button className="primary" onClick={()=>setDone(!done)}>{done?'✓ Completed':'Complete today'}</button><div className="streak">●━━━━●━━━━●━━━━●━━━━●</div><Heat colors={palette.habits}/></article></div></Page>}
function Fasting(){const[start,setStart]=useState(()=>load('fastStart',null)),[now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);const h=start?(now-start)/36e5:0;return <Page title="Fasting" sub="Actual time and estimated metabolic equivalent remain separate."><article className="fast"><div className="ring"><strong>{h.toFixed(2)}h</strong><small>actual elapsed</small></div><button className="primary" onClick={()=>{if(start){setStart(null);save('fastStart',null)}else{const n=Date.now();setStart(n);save('fastStart',n)}}}>{start?'End fast':'Start fast'}</button><p>Exercise effect is an educational estimate, not a biological measurement.</p></article></Page>}
function Sports(){const[items,setItems]=useState(()=>load('sports',[])),[title,setTitle]=useState(''),[photo,setPhoto]=useState(null);function add(){const n=[{id:id(),title:title||'Activity',photo:photo?URL.createObjectURL(photo):null,date:new Date().toISOString()},...items];setItems(n);save('sports',n);setTitle('');setPhoto(null)}return <Page title="Sports" sub="Photo-led activities, colourful fallbacks and performance details."><div className="form card"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Activity title"/><div className="fields"><input placeholder="Duration minutes"/><input placeholder="Distance km"/><input placeholder="Calories"/><input placeholder="Average HR"/></div><label><Upload/>Choose photo<input hidden type="file" accept="image/*" onChange={e=>setPhoto(e.target.files?.[0])}/></label><button className="primary" onClick={add}>Save activity</button></div><div className="sports">{[...items,{title:'Cycling Commute'},{title:'Sunday Class Swim'},{title:'Tower Bridge Walk'}].map((x,i)=><article className="sport" key={x.id||i}><div className={'fallback f'+i} style={x.photo?{backgroundImage:`url(${x.photo})`}:{}}><Camera/></div><h3>{x.title}</h3><p>42 min · 14.6 km · 381 kcal · 142 bpm</p></article>)}</div></Page>}
function Gratitude(){const[notes,setNotes]=useState(()=>load('notes',[])),[body,setBody]=useState(''),[photo,setPhoto]=useState(null);function add(){if(!body)return;const n=[{id:id(),body,photo:photo?URL.createObjectURL(photo):null,date:new Date().toISOString()},...notes];setNotes(n);save('notes',n);setBody('');setPhoto(null)}return <Page title="Grateful" sub="Capture a note immediately, with an optional photo."><div className="form card"><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="What are you grateful for?"/><label><Camera/>Attach photo<input hidden type="file" accept="image/*" onChange={e=>setPhoto(e.target.files?.[0])}/></label><button className="primary" onClick={add}>Save gratitude note</button></div><div className="notes">{notes.map(n=><article className="card" key={n.id}>{n.photo&&<img src={n.photo}/>}<small>{new Date(n.date).toLocaleString()}</small><p>{n.body}</p></article>)}</div></Page>}
function Exercises(){const[q,setQ]=useState(''),[active,setActive]=useState(null);const list=exercises.filter(x=>x.toLowerCase().includes(q.toLowerCase()));return <Page title="Exercises" sub="Search the catalogue and start a compact Routine Player."><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search exercise or category"/></div><div className="catalog">{list.map(x=><button onClick={()=>setActive(x)}>{x}<ChevronRight/></button>)}</div>{active&&<div className="drawer"><button className="close" onClick={()=>setActive(null)}><X/></button><small>ROUTINE PLAYER</small><h2>{active}</h2><p>LIVE 00:00:04</p>{[1,2,3].map(n=><div className="set"><b>Set {n}</b><input defaultValue="10"/><input placeholder="kg"/><button>✓ Done</button></div>)}<button className="primary">Finish workout</button></div>}</Page>}
function Life(){const events=load('life',[]);return <Page title="My Life" sub="Calendar and unified daily timeline."><div className="calendar"><CalendarDays/><h2>September 2026</h2><div>{Array.from({length:30},(_,i)=><button className={i===5?'today':''}>{i+1}</button>)}</div></div><Panel icon={<History/>} title="Sunday, 6 September"><p>08:15 Sleep logged</p><p>09:40 Fast started</p><p>18:20 Walking goal exceeded</p><p>20:15 Gratitude note added</p></Panel></Page>}
function HistoryPage(){return <Page title="Log History" sub="Search, filter and review all saved records."><div className="quick"><input placeholder="Search logs"/><select><option>All records</option><option>Health</option><option>Habits</option><option>Workouts</option><option>Fasting</option><option>Gratitude</option></select></div><List rows={[["Sleep","7h 28m","Today 08:15"],["Fast","Started","Today 09:40"],["Walk","37 minutes","Today 18:20"],["Gratitude","Note added","Today 20:15"]]}/></Page>}
function List({rows}){return <div className="list">{rows.map((r,i)=><article className="card" key={i}><b>{r[0]}</b><span>{r[1]}</span><small>{r[2]}</small></article>)}</div>}
function SettingsPage({theme,setTheme,avatar,setAvatar,tz,setTz}){return <Page title="Settings" sub="Appearance, profile, timezone, dashboard layout and synchronization."><div className="settings"><article className="card"><h3>Profile photo</h3><label className="avatar">{avatar?<img src={avatar}/>:<b>AS</b>}<Camera/><input hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)setAvatar(URL.createObjectURL(f))}}/></label></article><article className="card"><h3>Six themes</h3><div className="themegrid">{themes.map(t=><button className={t===theme?'selected':''} onClick={()=>setTheme(t)}>{t}</button>)}</div></article><article className="card"><h3>Date, time and region</h3><select value={tz} onChange={e=>setTz(e.target.value)}><option>Europe/London</option><option>Europe/Paris</option><option>America/New_York</option><option>Asia/Manila</option><option>Australia/Sydney</option></select><label><input type="checkbox" defaultChecked/> Show live seconds</label><label><input type="checkbox" defaultChecked/> Week starts Monday</label></article><article className="card"><h3>Dashboard layout</h3><p>Drag mode, widget sizes, hide and restore are prepared for cloud persistence.</p><button className="primary">Customise dashboard</button></article></div></Page>}
function Page({title,sub,children}){return <><h2 className="pagetitle">{title}</h2><p className="muted">{sub}</p>{children}</>}
export default function App(){const[page,setPage]=useState(()=>location.hash.slice(1)||'snapshot'),[theme,setTheme]=useState(()=>load('theme','forest')),[avatar,setAvatar]=useState(null),[tz,setTz]=useState('Europe/London'),[time,setTime]=useState(new Date()),[menu,setMenu]=useState(false);useEffect(()=>{const t=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(t)},[]);useEffect(()=>{save('theme',theme)},[theme]);const hour=+new Intl.DateTimeFormat('en-GB',{hour:'2-digit',hour12:false,timeZone:tz}).format(time),g=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening',day=new Intl.DateTimeFormat('en-GB',{weekday:'long',timeZone:tz}).format(time),date=new Intl.DateTimeFormat('en-GB',{
weekday:'short',
day:'numeric',
month:'long',
year:'numeric',
hour:'2-digit',
minute:'2-digit',
second:'2-digit',
hour12:false,
timeZone:tz,
timeZoneName:'short'
}).format(time);function go(k){setPage(k);location.hash=k;setMenu(false)}let body={snapshot:<SnapshotPageV1/>,life:<MyLifePage/>,health:<HealthMetricsPage/>,exercises:<ExercisesPage/>,sports:<SportsPage/>,habits:<HabitsPage/>,fasting:<FastingPage/>,history:<LogHistoryPage/>,grateful:<GratefulPage/>,settings:<NewSettingsPage/>}[page]||<Snapshot/>;return <div className={'app theme-'+theme}><aside className={menu?'open':''}><div className="brand"><Leaf/>fitlife</div><div className="profile">{avatar?<img src={avatar}/>:<b>AS</b>}<div><strong>Abner Serania</strong><small>Synced across devices</small></div></div><nav>{nav.map((n,i)=><button className={page===keys[i]?'active':''} onClick={()=>go(keys[i])}>{n}</button>)}</nav></aside><main><header><button className="menubtn" onClick={()=>setMenu(!menu)}><Menu/></button><div><h1>{g}, Abner</h1><p>Happy {day}</p><small>{date}</small></div><div className="actions"><button><Cloud/>Synced</button><button onClick={()=>go('grateful')}><BookHeart/>Gratitude note</button><button className="primary"><Plus/>Log day</button></div></header>{body}</main></div>}

