import { supabase } from '../../lib/supabaseClient'
const KEY='fitlife-sports-entries',HISTORY='fitlife-log-history'
const seed=[{id:'sport-1',category:'Cycling',title:'Cycling Commute',entry_date:'2026-09-06',start_time:'17:38',end_time:'18:20',duration_minutes:42,distance_km:14.6,calories:381,average_hr:142,max_hr:168,rpe:6,notes:'Steady commute through the city.',photos:[],featured_index:0,position_x:50,position_y:50,sync_status:'synced'},{id:'sport-2',category:'Swimming',title:'Sunday Class Swim',entry_date:'2026-09-04',start_time:'10:00',end_time:'10:42',duration_minutes:42,distance_km:.7,calories:250,average_hr:134,max_hr:154,rpe:5,notes:'Technique-focused pool session.',photos:[],featured_index:0,position_x:50,position_y:50,sync_status:'synced'}]
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||seed}catch{return seed}};const write=rows=>{localStorage.setItem(KEY,JSON.stringify(rows));window.dispatchEvent(new CustomEvent('fitlife:sports-changed',{detail:rows}))}
function history(row,remove=false){let rows=[];try{rows=JSON.parse(localStorage.getItem(HISTORY)||'[]')}catch{}const id=`sports:${row.id}`;rows=rows.filter(x=>x.id!==id);if(!remove)rows.unshift({id,source_id:row.id,type:'Sports',title:row.title,date:row.entry_date,time:row.start_time,displayDate:row.entry_date,summary:`${row.duration_minutes||0} min · ${row.distance_km||0} km · ${row.calories||0} kcal`,status:row.sync_status||'pending'});localStorage.setItem(HISTORY,JSON.stringify(rows));window.dispatchEvent(new CustomEvent('fitlife:history-changed',{detail:rows}))}
async function user(){if(!supabase)return null;const{data}=await supabase.auth.getUser();return data.user}
export async function listSports(){const u=await user();if(u){const{data,error}=await supabase.from('sports_entries').select('*, sports_media(*)').is('deleted_at',null).order('entry_date',{ascending:false});if(!error&&data){const rows=data.map(r=>({...r,photos:(r.sports_media||[]).map(m=>({id:m.id,path:m.storage_path,is_featured:m.is_featured}))}));write(rows);return rows}}return read()}
export async function saveSport(entry,media){const u=await user();const row={...entry,id:entry.id||crypto.randomUUID(),photos:media.photos||entry.photos||[],featured_index:media.featured||0,position_x:media.positionX,position_y:media.positionY,sync_status:u?'syncing':navigator.onLine?'local':'offline',updated_at:new Date().toISOString()};let rows=[row,...read().filter(x=>x.id!==row.id)];write(rows);history(row);if(!u)return row;const payload={...row,user_id:u.id,photos:undefined,sync_status:undefined};const{error}=await supabase.from('sports_entries').upsert(payload,{onConflict:'id'});if(error){row.sync_status='failed';write([row,...rows.filter(x=>x.id!==row.id)]);return row}for(let i=0;i<(media.files||[]).length;i++){const file=media.files[i];const path=`${u.id}/sports/${row.id}/${crypto.randomUUID()}.webp`;const{error:up}=await supabase.storage.from('activity-media').upload(path,file,{contentType:file.type||'image/webp'});if(!up)await supabase.from('sports_media').insert({user_id:u.id,sports_id:row.id,storage_path:path,sort_order:i,is_featured:i===media.featured})}row.sync_status='synced';write([row,...rows.filter(x=>x.id!==row.id)]);history(row);return row}
export async function deleteSport(row){write(read().filter(x=>x.id!==row.id));history(row,true);const u=await user();if(u)await supabase.from('sports_entries').update({deleted_at:new Date().toISOString()}).eq('id',row.id)}
export function subscribeSports(cb){if(!supabase)return()=>{};const ch=supabase.channel('sports-cross-device').on('postgres_changes',{event:'*',schema:'public',table:'sports_entries'},()=>listSports().then(cb)).subscribe();return()=>supabase.removeChannel(ch)}
